// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The structured half of an approval request: what the dialog draws.
 *
 * One variant per tool, so the dialog renders a file path with a size or a
 * command line with its working directory, rather than a JSON blob the user
 * has to parse (PLAN 2.1, `ApprovalDetail`).
 */
export type ApprovalDetail = { "kind": "fs_list", 
/**
 * The resolved directory.
 */
path: string, } | { "kind": "fs_read", 
/**
 * The resolved file.
 */
path: string, 
/**
 * Its size, or `None` when it does not exist yet.
 *
 * Exported as a `number` rather than a `bigint`: this crosses the IPC
 * boundary as JSON, where it is already a double, and a `bigint` in
 * the binding would be a type the value never has at runtime.
 */
bytes: number | null, } | { "kind": "fs_write", 
/**
 * The resolved target.
 */
path: string, 
/**
 * How much would be written. A `number` on the wire — see
 * [`ApprovalDetail::FsRead::bytes`].
 */
bytes: number, 
/**
 * Whether this overwrites something.
 */
exists: boolean, 
/**
 * The first few kilobytes of the content, for the diff pane.
 */
preview: string | null, } | { "kind": "shell", 
/**
 * The program as the model named it.
 */
program: string, 
/**
 * Its arguments, unjoined.
 */
args: Array<string>, 
/**
 * The resolved working directory.
 */
cwd: string, 
/**
 * A display-only rendering of the whole command.
 *
 * Never executed and never parsed: `shell_exec` spawns `program` with
 * `args` directly, with no shell in between (PLAN 5.1). This string
 * exists so a user can read one line instead of five fields.
 */
shell_line: string, } | { "kind": "screen", 
/**
 * Which display, named the way the dialog should say it.
 */
display: string, 
/**
 * Physical width in pixels, `0` when the geometry is not known yet.
 */
width: number, 
/**
 * Physical height in pixels, `0` when the geometry is not known yet.
 */
height: number, };

/**
 * One approval, as the dialog receives it (PLAN 2.1, `ApprovalRequest`).
 *
 * Half of this comes from [`AskRequest`] — the wording, the badge, the
 * structured detail, the scope — and half is added here: the id to answer
 * with, and the window during which answering it means anything.
 */
export type ApprovalRequest = { 
/**
 * What `approval_resolve` is called with.
 */
request_id: string, 
/**
 * The session whose turn is blocked.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * The tool being asked about.
 */
tool: string, 
/**
 * The badge. Advisory only (PLAN 3.3).
 */
risk: Risk, 
/**
 * The dialog's title: "Write file", "Run shell command".
 */
title: string, 
/**
 * One line naming the thing.
 */
summary: string, 
/**
 * The structured detail the dialog draws.
 */
detail: ApprovalDetail, 
/**
 * What "allow for this session" would cover, in words.
 */
scope_label: string, 
/**
 * Whether `allow_session` is offered at all (PLAN 3.1).
 */
session_grant_allowed: boolean, 
/**
 * Why policy is asking.
 */
reason: string, 
/**
 * When it was raised, fixed-width UTC RFC3339.
 */
requested_at: string, 
/**
 * When it stops being answerable.
 */
expires_at: string, };

/**
 * How a tool call came to run, or not (PLAN 2.1, `AuditEntry.decision`).
 */
export type AuditDecision = "auto" | "allow_once" | "allow_session" | "deny";

/**
 * One line of the log.
 *
 * Serialized and deserialized with the same struct on purpose: the file *is*
 * the wire format for `audit_tail`, so a field the writer adds is a field the
 * reader sees, and there is no second shape to keep in step.
 */
export type AuditEntry = { 
/**
 * RFC3339, UTC, millisecond precision — fixed width, so the file sorts
 * lexicographically in the order it was written.
 */
ts: string, 
/**
 * Which session made the call.
 */
session_id: string, 
/**
 * Which turn within it.
 */
turn_id: string, 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * Tool name.
 */
tool: string, 
/**
 * Auto-allowed, approved, or refused.
 */
decision: AuditDecision, 
/**
 * Why policy decided that, in the words the user was shown.
 */
policy_reason: string, 
/**
 * SHA-256 of the canonical arguments JSON, hex.
 *
 * The digest is over the arguments in full, including anything the
 * redacted copy shortened, so two calls can be compared for identity even
 * though neither line quotes what they carried.
 */
args_digest: string, 
/**
 * The arguments as JSON, paths kept and values shortened.
 */
args_redacted: string, 
/**
 * How it ended.
 */
outcome: Outcome, 
/**
 * Wall-clock duration of the execution itself.
 */
duration_ms: number, 
/**
 * Bytes the call carried in — the content of a write, nothing for a read.
 */
bytes_in: number, 
/**
 * Bytes the call produced, before any truncation for the model.
 */
bytes_out: number, 
/**
 * The stable code when this failed, `null` otherwise.
 */
error_code: string | null, };

/**
 * What the user answered (PLAN 2.1, `Decision`).
 */
export type Decision = "allow_once" | "allow_session" | "deny";

/**
 * One `allow_session` grant.
 *
 * The variants are the scopes, not the tools: `fs_read` appears only as
 * [`Grant::FsReadLarge`] because the only `fs_read` row that offers a grant
 * is the large-file one, and a grant that covered every read would be a
 * different, much broader thing than what the user was asked about.
 */
export type Grant = { "kind": "fs_read_large" } | { "kind": "fs_write" } | { "kind": "shell", 
/**
 * The normalized program key — see [`Grant::shell`].
 */
program: string, } | { "kind": "screen_capture" };

/**
 * One message in a transcript.
 */
export type Message = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * Who produced it.
 */
role: Role, 
/**
 * The text. Empty for an assistant message that only made tool calls.
 */
text: string, 
/**
 * The calls this message made. Assistant messages only.
 */
tool_calls: Array<ToolCallRecord>, 
/**
 * Which call this message answers. `tool` messages only.
 */
tool_call_id: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, };

/**
 * How a tool call ended (PLAN 2.1, `AuditEntry.outcome`).
 */
export type Outcome = "ok" | "error" | "denied" | "cancelled";

/**
 * A project as the UI sees it.
 */
export type Project = { 
/**
 * UUID v4, stable for the life of the project.
 */
id: string, 
/**
 * Display name. Defaults to the workspace folder name.
 */
name: string, 
/**
 * Canonicalized absolute path, free of Windows verbatim prefixes.
 */
workspace_path: string, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. `None` until the project has been opened once.
 */
last_opened_at: string | null, 
/**
 * Whether the workspace folder is present *right now*. Never stored.
 */
workspace_exists: boolean, };

/**
 * What opening a project yields: the project plus its sessions, newest first.
 */
export type ProjectDetail = { project: Project, 
/**
 * The project's sessions, newest first.
 *
 * Filled by the command layer rather than by [`Store::open`]: a summary
 * carries the session's *live* state, and only [`AppState`] can see both
 * the session document and the turns currently running.
 *
 * [`AppState`]: crate::state::AppState
 */
sessions: Array<SessionSummary>, };

/**
 * Who or what produced an answer (PLAN 2.2, `tool:approval_resolved`).
 */
export type ResolvedBy = "user" | "policy" | "timeout";

/**
 * How alarming a call should look in the approval dialog.
 *
 * Advisory only: the risk badge changes the wording and the colour, never
 * whether something is asked about. Nothing downstream branches on it.
 */
export type Risk = "low" | "medium" | "high";

/**
 * Who produced a message.
 */
export type Role = "user" | "assistant" | "tool" | "system";

/**
 * A session and its transcript.
 */
export type SessionDetail = { 
/**
 * The session itself.
 */
session: SessionSummary, 
/**
 * Oldest first — the order the transcript is read in.
 */
messages: Array<Message>, 
/**
 * Approvals this session is blocked on.
 *
 * Filled by [`AppState::session_detail`](crate::AppState::session_detail)
 * rather than here: the transcript is on disk, and what a session is
 * waiting for is a fact about this process. It is on the detail at all so
 * that a window reopened mid-turn re-draws the dialog it missed, instead
 * of leaving a turn blocked on a prompt nobody can see.
 */
pending_approvals: Array<ApprovalRequest>, };

/**
 * Lifecycle of a session.
 *
 * Derived from the turn registry on every read, never stored — see the module
 * documentation.
 */
export type SessionState = "idle" | "running" | "awaiting_approval" | "error";

/**
 * One row of a project's session list.
 *
 * `state` is live and `message_count` is derived; neither is stored.
 */
export type SessionSummary = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * The project this session belongs to.
 */
project_id: string, 
/**
 * Display title. Taken from the first user message when not given.
 */
title: string, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. Bumped by every message and every rename.
 */
updated_at: string, 
/**
 * How many messages the transcript holds.
 */
message_count: number, 
/**
 * What the session is doing *right now*.
 */
state: SessionState, };

/**
 * Why a model stopped.
 */
export type StopReason = "stop" | "tool_calls" | "cancelled" | "length" | "error";

/**
 * `tool:approval_resolved` — an approval stopped being pending.
 *
 * Emitted for every way one can end, not only for a click: a turn that was
 * cancelled while waiting and a request that expired both produce this, with
 * `resolved_by` saying which. A UI that only removed a card on the user's own
 * answer would leave a dialog on screen for a call nothing will ever run.
 */
export type ToolApprovalResolved = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The request that was answered.
 */
request_id: string, 
/**
 * The call it was about.
 */
call_id: string, 
/**
 * What was decided.
 */
decision: Decision, 
/**
 * Who decided it.
 */
resolved_by: ResolvedBy, };

/**
 * One tool call, as the transcript records it.
 *
 * `args_json` is what the model actually sent, kept verbatim so the card in
 * the UI shows the call that was made rather than the call policy resolved.
 * `summary` is the one human line — never a raw blob, because a transcript
 * that inlines 200 KB of file content is a transcript nobody scrolls.
 */
export type ToolCallRecord = { 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * Tool name: `fs_list`, `fs_read`, `fs_write`, ...
 */
tool: string, 
/**
 * The arguments as the model sent them, as a JSON string.
 */
args_json: string, 
/**
 * How far it got.
 */
status: ToolCallStatus, 
/**
 * One human line naming the result, or `null` before there is one.
 */
summary: string | null, };

/**
 * How far one tool call got.
 */
export type ToolCallStatus = "pending" | "approved" | "denied" | "running" | "ok" | "error" | "cancelled";

/**
 * `tool:finished` — the call ended, whatever became of it.
 */
export type ToolFinished = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * How it ended.
 */
outcome: Outcome, 
/**
 * The one human line. Never a raw blob.
 */
summary: string, 
/**
 * How long the execution itself took.
 */
duration_ms: number, 
/**
 * Whether the result the model saw was shorter than what was available.
 */
truncated: boolean, };

/**
 * `tool:requested` — the model asked, before policy has judged it.
 */
export type ToolRequested = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The model's id for the call.
 */
call_id: string, 
/**
 * The tool name.
 */
tool: string, 
/**
 * The arguments, redacted the way the audit log redacts them: paths kept
 * whole, long values shortened, file content replaced by its size.
 */
args_redacted: string, };

/**
 * `tool:started` — policy cleared it and it is running.
 */
export type ToolStarted = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * The tool name.
 */
tool: string, };

/**
 * Payload of [`EVENT_TRAY_ACTIVATE`].
 *
 * `action` is `"show"` today. PLAN 2.2 also lists `"new_session"`, for a tray
 * item that starts a session directly; the menu has no such item yet, so the
 * variant is not invented here — a payload the runtime never sends is a
 * branch the UI would carry for nothing.
 */
export type TrayActivate = { 
/**
 * Why the window came forward.
 */
action: string, };

/**
 * `turn:delta` — a frame of assistant text.
 *
 * Deltas are coalesced into roughly 50 ms frames before they are sent
 * (PLAN 4.2), so this is a phrase rather than a token: waking the WebView
 * once per token is what makes a streamed reply feel slower than a batched
 * one.
 */
export type TurnDelta = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Per-turn monotonic counter. The UI drops anything out of order or
 * repeated, which is what makes re-syncing after a reload safe.
 */
seq: number, 
/**
 * The text to append.
 */
text: string, };

/**
 * `turn:error`.
 *
 * Always followed by a `turn:finished` carrying [`StopReason::Error`], so a
 * UI that only tracks the lifecycle does not have to special-case failure to
 * re-enable its composer.
 */
export type TurnError = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * A stable code from PLAN 4.4.
 */
code: string, 
/**
 * What went wrong, written for the user.
 */
message: string, 
/**
 * Whether sending the same thing again could work.
 */
retryable: boolean, };

/**
 * `turn:finished`.
 */
export type TurnFinished = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Why it ended.
 */
stop_reason: StopReason, 
/**
 * What it cost, when the provider said.
 */
usage: Usage | null, };

/**
 * What `session_send` hands back (PLAN 2.1).
 *
 * The turn itself is reported through events; this is only the handle needed
 * to cancel it.
 */
export type TurnHandle = { 
/**
 * The session the turn runs in.
 */
session_id: string, 
/**
 * The turn, unique within the process.
 */
turn_id: string, };

/**
 * `turn:message` — an assistant message, finalized and on disk.
 */
export type TurnMessage = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The message as it was persisted. Replaces the streamed buffer.
 */
message: Message, };

/**
 * `turn:started`.
 */
export type TurnStarted = { 
/**
 * The session the turn runs in.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Which model is answering.
 */
model: string, };

/**
 * What a turn cost, when the provider says.
 */
export type Usage = { 
/**
 * Tokens in the request.
 */
prompt_tokens: number, 
/**
 * Tokens in the reply.
 */
completion_tokens: number, 
/**
 * Their sum, as the provider reported it.
 */
total_tokens: number, };
