// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An identity, as the UI and the runtime see it.
 */
export type Agent = { 
/**
 * UUID v4, or [`DEFAULT_AGENT_ID`] for the built-in one.
 */
id: string, 
/**
 * Display name: "Reviewer", "Scribe".
 */
name: string, 
/**
 * What this identity is for, in one line.
 */
role: string, 
/**
 * What it carries into every system message; empty for the built-in one.
 */
instructions: string, 
/**
 * Which provider answers for it. [`DEFAULT_PROVIDER_ID`] today.
 */
provider_id: string, 
/**
 * The tools it may call, in registry order: the only schemas shown, and
 * policy refuses the rest.
 */
tools: Array<string>, 
/**
 * The skills it may run (Phase 13). Never widens [`Agent::tools`]; empty
 * for the built-in identity.
 */
skills: Array<string>, 
/**
 * Most scheduled runs it may make in a day (Phase 16); zero means never
 * scheduled.
 */
runs_per_day: number, 
/**
 * Whether this is the built-in identity, which cannot be edited or
 * deleted. Derived, never stored.
 */
builtin: boolean, };

/**
 * What a create or an update carries.
 */
export type AgentDraft = { 
/**
 * Display name. Trimmed, and unique among identities.
 */
name: string, 
/**
 * What this identity is for, in one line.
 */
role: string, 
/**
 * What it carries into every request. May be empty.
 */
instructions: string, 
/**
 * Which provider answers for it.
 */
provider_id: string, 
/**
 * Tool names from the registry. May be empty — an identity that only reads
 * and writes prose is a useful thing to be able to make.
 */
tools: Array<string>, 
/**
 * The runbooks it may run. Requires `skill_run` and `skill_return` in
 * [`AgentDraft::tools`] when it is not empty.
 */
skills: Array<string>, 
/**
 * Most scheduled runs a day, capped at [`AGENT_RUNS_PER_DAY_MAX`];
 * defaulted for older callers.
 */
runs_per_day: number, };

/**
 * What the approval dialog draws: one variant per tool, so the user reads a
 * path or a command line rather than JSON (PLAN 2.1).
 */
export type ApprovalDetail = { "kind": "fs_list", 
/**
 * The resolved directory.
 */
path: string, } | { "kind": "fs_read", 
/**
 * The resolved file.
 */
path: string, 
/**
 * Its size, or `None` when it does not exist yet. A `number` in the
 * binding: over JSON it is never a `bigint`.
 */
bytes: number | null, } | { "kind": "fs_write", 
/**
 * The resolved target.
 */
path: string, 
/**
 * How much would be written. A `number` on the wire — see
 * [`ApprovalDetail::FsRead::bytes`].
 */
bytes: number, 
/**
 * Whether this overwrites something.
 */
exists: boolean, 
/**
 * The first few kilobytes of the content, for the diff pane.
 */
preview: string | null, 
/**
 * The skill this write would make live, when it applies a proposal
 * (PLAN 7.13).
 */
applies: string | null, } | { "kind": "shell", 
/**
 * The program as the model named it.
 */
program: string, 
/**
 * Its arguments, unjoined.
 */
args: Array<string>, 
/**
 * The resolved working directory.
 */
cwd: string, 
/**
 * The whole command on one line, for reading only: never executed or
 * parsed (PLAN 5.1).
 */
shell_line: string, 
/**
 * The distribution and its working directory, when the project has
 * an execution host (PLAN 7.12). `cwd` is then still the folder
 * containment was judged against, but not where the command starts,
 * so the dialog shows both.
 */
host: ExecTarget | null, } | { "kind": "screen", 
/**
 * Which display, named the way the dialog should say it.
 */
display: string, 
/**
 * Physical width in pixels — the size of the file — or `0` when
 * unknown. The logical size sits beside it because the two differ on
 * a scaled display (PLAN 5.1).
 */
width: number, 
/**
 * Physical height in pixels, `0` when the geometry is not known.
 */
height: number, 
/**
 * Width in the display's own points — what the user calls its size.
 */
logical_width: number, 
/**
 * Height in the display's own points.
 */
logical_height: number, } | { "kind": "memory", 
/**
 * `preference`, `exception` or `convention`. Not `kind`, which is
 * this enum's tag on the wire.
 */
memory_kind: string, 
/**
 * Exactly what would be remembered.
 */
text: string, 
/**
 * What it would rest on, when the model named something.
 */
source: string | null, } | { "kind": "handoff", 
/**
 * One row per brief, in the order they would go out.
 */
briefs: Array<HandoffRow>, 
/**
 * The identity that would review what comes back, when one was named.
 */
reviewer: string | null, 
/**
 * Where the briefs would be filed, when the workspace has a `.aegis/briefs/`.
 */
filed_in: string | null, } | { "kind": "connector", 
/**
 * The connector's id — the part before the `__`.
 */
connector: string, 
/**
 * The connector's name, as the person who installed it wrote it.
 */
connector_name: string, 
/**
 * The tool's own name, as the server spells it.
 */
tool: string, 
/**
 * What the server says the tool does. The server's words, not ours.
 */
description: string, 
/**
 * Whether the server claims the tool only reads. A claim, attributed.
 */
read_only_hint: boolean, 
/**
 * The arguments the model wrote, as indented JSON.
 */
arguments: string, };

/**
 * One approval, as the dialog receives it (PLAN 2.1, `ApprovalRequest`).
 *
 * [`AskRequest`]'s content plus the id and the answerable window.
 */
export type ApprovalRequest = { 
/**
 * What `approval_resolve` is called with.
 */
request_id: string, 
/**
 * The session whose turn is blocked.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * The tool being asked about.
 */
tool: string, 
/**
 * The badge. Advisory only (PLAN 3.3).
 */
risk: Risk, 
/**
 * The dialog's title: "Write file", "Run shell command".
 */
title: string, 
/**
 * One line naming the thing.
 */
summary: string, 
/**
 * The structured detail the dialog draws.
 */
detail: ApprovalDetail, 
/**
 * What "allow for this session" would cover, in words.
 */
scope_label: string, 
/**
 * Whether `allow_session` is offered at all (PLAN 3.1).
 */
session_grant_allowed: boolean, 
/**
 * Why policy is asking.
 */
reason: string, 
/**
 * When it was raised, fixed-width UTC RFC3339.
 */
requested_at: string, 
/**
 * When it stops being answerable.
 */
expires_at: string, };

/**
 * A file a tool call left on disk, identified by path, digest and size —
 * never a copy (PLAN 5.4). Only `screen_capture` produces one today.
 */
export type AuditArtifact = { 
/**
 * Where the file was written.
 */
path: string, 
/**
 * SHA-256 of the bytes on disk, hex.
 */
sha256: string, 
/**
 * Width in pixels.
 */
width: number, 
/**
 * Height in pixels.
 */
height: number, };

/**
 * How a tool call came to run, or not (PLAN 2.1, `AuditEntry.decision`).
 */
export type AuditDecision = "auto" | "allow_once" | "allow_session" | "deny" | "operator";

/**
 * One line of the log, and the `audit_tail` wire format. Later fields default
 * so older lines still parse.
 */
export type AuditEntry = { 
/**
 * RFC3339, UTC, millisecond precision — fixed width, so the file sorts
 * lexicographically in the order it was written.
 */
ts: string, 
/**
 * Which session made the call.
 */
session_id: string, 
/**
 * Which identity it was made as (Phase 12); empty on older lines.
 */
agent_id: string, 
/**
 * Which turn within it.
 */
turn_id: string, 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * Tool name.
 */
tool: string, 
/**
 * The skill run this call belongs to (Phase 13; PLAN 7.6): every call
 * between `skill_run` and `skill_return`. Empty otherwise.
 */
skill: string, 
/**
 * The delegation this call belongs to (Phase 15): the CoS's
 * `handoff_delegate` and every call specialists make on its briefs.
 */
handoff: string, 
/**
 * The routine whose run this call belongs to (Phase 16).
 */
routine: string, 
/**
 * Auto-allowed, approved, or refused.
 */
decision: AuditDecision, 
/**
 * Why policy decided that, in the words the user was shown.
 */
policy_reason: string, 
/**
 * SHA-256 of the full canonical arguments JSON, hex — including what the
 * redacted copy shortened.
 */
args_digest: string, 
/**
 * The arguments as JSON, paths kept and values shortened.
 */
args_redacted: string, 
/**
 * How it ended.
 */
outcome: Outcome, 
/**
 * Wall-clock duration of the execution itself.
 */
duration_ms: number, 
/**
 * Bytes the call carried in — the content of a write, nothing for a read.
 */
bytes_in: number, 
/**
 * Bytes the call produced, before any truncation for the model.
 */
bytes_out: number, 
/**
 * The stable code when this failed, `null` otherwise.
 */
error_code: string | null, 
/**
 * The file this call wrote, when it wrote one.
 */
artifact: AuditArtifact | null, };

/**
 * How a configured provider authenticates.
 *
 * Names a credential source, never a token. `api_key`: keyring or
 * `AEGIS_API_KEY` for an OpenAI-compatible host; [`AuthKind::Gemini`]: same
 * store, Google's API; CLI variants reuse an existing login.
 */
export type AuthKind = "api_key" | "gemini" | "claude_cli" | "codex_cli" | "grok_cli";

/**
 * The URL and model Settings prefills for one [`AuthKind`].
 *
 * Used when the user switches authentication.
 */
export type AuthPreset = { 
/**
 * Which login this row describes.
 */
auth_kind: AuthKind, 
/**
 * Endpoint used when the base URL field is left empty.
 */
default_base_url: string, 
/**
 * Model id prefilled when the field is empty or still the previous kind's
 * default.
 */
default_model: string, };

/**
 * The board of one project.
 */
export type Board = { 
/**
 * The project it is the board of.
 */
project_id: string, 
/**
 * Where `STATUS.md` is, when it is there. Empty when the convention has
 * not been laid down in this workspace, which is a thing the panel says
 * rather than an error.
 */
status_path: string, 
/**
 * A person has to do something.
 */
attention: Array<BoardItem>, 
/**
 * Something is running.
 */
in_flight: Array<BoardItem>, 
/**
 * Something stopped short.
 */
blocked: Array<BoardItem>, 
/**
 * Every run in the window, newest first.
 */
runs: Array<Run>, 
/**
 * What every session of the project has spent — not just the runs in the
 * audit window.
 */
cost: Cost, };

/**
 * One line of the board.
 *
 * `BoardItem` on the wire: the generated bindings share one namespace.
 */
export type BoardItem = { 
/**
 * The line itself.
 */
text: string, 
/**
 * What is worth knowing beside it: a reason, a runbook, an identity.
 * Empty when the line says it all.
 */
detail: string, 
/**
 * Where it came from.
 */
source: BoardSource, 
/**
 * RFC3339 UTC, when the runtime knows. Empty for a line of the file,
 * which carries no time of its own.
 */
at: string, 
/**
 * The session to open. Empty when there is none to open.
 */
session_id: string, 
/**
 * The routine this is about. Empty when it is not about one.
 */
routine_id: string, 
/**
 * The run to trace, when this line has one.
 */
run: RunRef | null, };

/**
 * Where a line on the board came from.
 *
 * On every item, since the file and the runtime are not equally current.
 */
export type BoardSource = "status" | "approval" | "session" | "routine" | "run";

/**
 * One file that arrived.
 */
export type BriefArrival = { 
/**
 * The name it had where the operator keeps it.
 */
from: string, 
/**
 * Where it is now, relative to the workspace root.
 */
path: string, 
/**
 * How much was copied.
 */
bytes: number, };

/**
 * One file that did not.
 */
export type BriefRefusal = { 
/**
 * The name it had where the operator keeps it.
 */
name: string, 
/**
 * Why it was not copied, in words somebody can act on.
 */
reason: string, };

/**
 * What a session has folded (Phase 14): a pointer and derived state, never a
 * deletion ([`compact`](crate::compact)).
 */
export type Compaction = { 
/**
 * The last message that folds. Everything after it still reaches the
 * model.
 */
through_message_id: string, 
/**
 * How many messages folded.
 */
folded: number, 
/**
 * What they became: goal, files, decisions, blockers.
 */
state: string, 
/**
 * RFC3339, UTC.
 */
at: string, };

/**
 * One external MCP server, as it is stored.
 */
export type Connector = { 
/**
 * Stable id, and the namespace its tools are offered under.
 */
id: string, 
/**
 * How it is named to a person. Never reaches a tool name.
 */
name: string, 
/**
 * The program to run. Looked up on PATH like any other.
 */
command: string, 
/**
 * Its arguments, passed as a vector — never through a shell.
 */
args: Array<string>, 
/**
 * Environment variables the server needs, by name.
 *
 * The values are read from Aegis' own environment when the child is
 * spawned. A name that is not set there is reported on the row rather
 * than passed as an empty string, because a server that reads an empty
 * token usually fails in a way that is much harder to read.
 */
env: Array<string>, 
/**
 * Whether Aegis starts it at all.
 */
enabled: boolean, };

/**
 * A connector as a person typed it into the form.
 */
export type ConnectorDraft = { 
/**
 * Stable id, and the namespace its tools are offered under.
 */
id: string, 
/**
 * How it is named to a person.
 */
name: string, 
/**
 * The program to run.
 */
command: string, 
/**
 * Its arguments.
 */
args: Array<string>, 
/**
 * Environment variables it needs, by name.
 */
env: Array<string>, 
/**
 * Whether Aegis starts it.
 */
enabled: boolean, };

/**
 * A connector and everything measured about it right now.
 *
 * The record from [`ConnectorStore`](crate::store::ConnectorStore) plus live
 * measurements, never stored.
 */
export type ConnectorView = { 
/**
 * The stored record.
 */
connector: Connector, 
/**
 * Where it is right now.
 */
state: State, 
/**
 * What it offers, when it is connected.
 */
tools: Array<ToolInfo>, 
/**
 * Why it is not connected, when it is not.
 */
error: string | null, 
/**
 * The last lines the server wrote to stderr, where start failures appear.
 */
log: Array<string>, 
/**
 * What the server said about itself, when it got that far.
 */
server: string | null, 
/**
 * The protocol version that was agreed.
 */
protocol: string | null, 
/**
 * Variables it names that this process's environment lacks (measured).
 */
missing_env: Array<string>, };

/**
 * Tokens spent over some turns (Phase 17). `unreported` is kept apart so a
 * total can read "at least".
 */
export type Cost = { 
/**
 * How many turns were summed.
 */
turns: number, 
/**
 * Of those, how many reported nothing.
 */
unreported: number, 
/**
 * Tokens into the model, cached ones included.
 */
prompt_tokens: number, 
/**
 * Of those, how many were served out of the prompt cache. The share of
 * `prompt_tokens` this is, is how well the prompt is holding its shape.
 */
cache_read_tokens: number, 
/**
 * Of those, how many were written to it.
 */
cache_creation_tokens: number, 
/**
 * Tokens out of it.
 */
completion_tokens: number, };

/**
 * What the user answered (PLAN 2.1, `Decision`).
 */
export type Decision = "allow_once" | "allow_session" | "deny";

/**
 * Why a session exists when a brief opened it (Phase 15): which delegation,
 * which session delegated, where the brief was filed. Otherwise an ordinary
 * session, visible in the sidebar.
 */
export type Delegated = { 
/**
 * The delegation this run belongs to. Shared with the audit lines.
 */
handoff_id: string, 
/**
 * The session whose turn handed the brief out.
 */
from_session_id: string, 
/**
 * Where the brief was filed, relative to the workspace. `None` without
 * `.aegis/briefs/`: the brief is then only the first message.
 */
brief: string | null, };

/**
 * What a row of the tree is.
 */
export type EntryKind = "dir" | "file" | "other";

/**
 * Where a project's commands run; stored as `Option<ExecHost>`, `None` being
 * this computer.
 */
export type ExecHost = { "kind": "wsl", 
/**
 * The distribution's name — `Ubuntu`, `Debian`, `Ubuntu-24.04`.
 */
distro: string, };

/**
 * One choice on the picker, where "this computer" is a row of its own.
 */
export type ExecHostOption = { "kind": "host" } | { "kind": "wsl", 
/**
 * The distribution's name.
 */
distro: string, };

/**
 * Where one command will actually land, once policy has resolved it.
 *
 * Built by policy and used by both the dialog and the tool, so what the user
 * reads is what runs.
 */
export type ExecTarget = { 
/**
 * The distribution the command runs in.
 */
distro: string, 
/**
 * The working directory, as a path inside that distribution.
 */
cwd: string, };

/**
 * One file, as the preview pane draws it.
 */
export type FilePreview = { 
/**
 * Relative to the workspace root, with `/`.
 */
path: string, 
/**
 * The file's own name.
 */
name: string, 
/**
 * Its size on disk.
 */
bytes: number, 
/**
 * When it last changed, RFC3339 UTC, when the filesystem says.
 */
modified: string | null, 
/**
 * Which part of the convention it is in.
 */
zone: Zone, 
/**
 * What there is to show.
 */
body: PreviewBody, };

/**
 * One `allow_session` grant. The variants are scopes, not tools.
 */
export type Grant = { "kind": "fs_read_large" } | { "kind": "fs_write" } | { "kind": "world_amend" } | { "kind": "shell", 
/**
 * The normalized program key — see [`Grant::shell`].
 */
program: string, } | { "kind": "screen_capture" } | { "kind": "memory_write" } | { "kind": "handoff_delegate" } | { "kind": "connector", 
/**
 * The full tool name the dialog named.
 */
tool: string, };

/**
 * One brief, as the approval dialog draws it.
 */
export type HandoffRow = { 
/**
 * What is to be achieved.
 */
goal: string, 
/**
 * The identity that would do it, as the model named it.
 */
owner: string, 
/**
 * `high`, `normal` or `low`.
 */
priority: string, 
/**
 * `status`, `artefact` or `question`.
 */
return_format: string, 
/**
 * How many paths and links it starts from.
 */
inputs: number, };

/**
 * What one drop did.
 *
 * Two lists, for the reason scaffold's report has two: the operator dropped
 * several things, and the answer to "did they all arrive" has to name the ones
 * that did not.
 */
export type ImportReport = { 
/**
 * Files copied into `.aegis/briefs/`, in the order they were dropped.
 */
arrived: Array<BriefArrival>, 
/**
 * Files left where they were, and why.
 */
refused: Array<BriefRefusal>, };

/**
 * Where the key in use came from (PLAN 2.1, `MaskedSettings`).
 */
export type KeySource = "keyring" | "env" | "claude_cli" | "codex_cli" | "grok_cli" | "none";

/**
 * What became of the last run.
 */
export type LastRun = { 
/**
 * When it started, RFC3339 UTC; intervals count from here.
 */
at: string, 
/**
 * The session it ran in, so the transcript is one click away.
 */
session_id: string, 
/**
 * How it ended.
 */
outcome: RunOutcome, 
/**
 * The run's own words: a return's summary, or what went wrong.
 */
detail: string, };

/**
 * Everything the WebView is allowed to know about the provider settings.
 *
 * No unmasked counterpart exists: a key is written or cleared, never read.
 */
export type MaskedSettings = { 
/**
 * How this provider authenticates.
 */
auth_kind: AuthKind, 
/**
 * The OpenAI-compatible base URL, normalized. Empty when unset.
 */
base_url: string, 
/**
 * The model id sent with every request. Empty when unset.
 */
model: string, 
/**
 * The output ceiling the provider's catalog reported for that model, or
 * `None` for an endpoint that does not publish one.
 *
 * Shown so a failed lookup (and a low default cap) is visible.
 */
max_output_tokens: number | null, 
/**
 * Which store answered when the key was last looked for.
 */
key_source: KeySource, 
/**
 * A few characters of the key, for recognition. `None` when there is no
 * key at all.
 */
key_hint: string | null, 
/**
 * Whether this machine has a credential store that answered.
 *
 * `false` on headless Linux or a locked keychain.
 */
keyring_available: boolean, 
/**
 * Prefill values for every authentication kind, so switching in the form
 * can fill the matching URL and model without a second round trip.
 */
presets: Array<AuthPreset>, };

/**
 * One memory, as the UI and the runtime see it.
 */
export type Memory = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * The identity this belongs to. No accessor spans two.
 */
agent_id: string, 
/**
 * Which of the three it is.
 */
kind: MemoryKind, 
/**
 * The memory itself, in one sentence.
 */
text: string, 
/**
 * What it rests on: a path, a ticket, a person. `None` for a preference
 * somebody simply stated.
 */
source: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. Bumped by a correction, and by a write that repeats
 * something already held.
 */
updated_at: string, };

/**
 * What a create or a correction carries.
 */
export type MemoryDraft = { 
/**
 * Which of the three this is.
 */
kind: MemoryKind, 
/**
 * The memory itself. Trimmed, and never empty.
 */
text: string, 
/**
 * What it rests on, when it rests on something nameable.
 */
source: string | null, };

/**
 * What a memory *is*. No `other`: anything else belongs in a file or a
 * runbook.
 */
export type MemoryKind = "preference" | "exception" | "convention";

/**
 * One message in a transcript.
 */
export type Message = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * Who produced it.
 */
role: Role, 
/**
 * The text. Empty for an assistant message that only made tool calls.
 */
text: string, 
/**
 * The calls this message made. Assistant messages only.
 */
tool_calls: Array<ToolCallRecord>, 
/**
 * Which call this message answers. `tool` messages only.
 */
tool_call_id: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, };

/**
 * What [`list`] found.
 */
export type ModelCatalog = { 
/**
 * Model ids the picker can offer, live ones first when the server answered.
 */
models: Array<string>, 
/**
 * Whether `models` came from the provider just now.
 */
live: boolean, 
/**
 * Empty on a live list. Otherwise why the fallback was used.
 */
message: string, };

/**
 * How a tool call ended (PLAN 2.1, `AuditEntry.outcome`).
 */
export type Outcome = "ok" | "error" | "denied" | "cancelled";

/**
 * What a preview shows.
 */
export type PreviewBody = { "kind": "text", 
/**
 * The first [`TEXT_MAX_BYTES`] of the file, decoded.
 */
text: string, 
/**
 * Whether the file is longer than `text`.
 */
truncated: boolean, 
/**
 * Whether the name says it is markdown.
 */
markdown: boolean, } | { "kind": "image", 
/**
 * The type its first bytes say it is.
 */
mime: string, } | { "kind": "binary", 
/**
 * The type its first bytes say it is, when they say.
 */
mime: string | null, };

/**
 * How soon a brief wants attention: three words, not an uncalibrated number.
 */
export type Priority = "high" | "normal" | "low";

/**
 * A project as the UI sees it.
 */
export type Project = { 
/**
 * UUID v4, stable for the life of the project.
 */
id: string, 
/**
 * Display name. Defaults to the workspace folder name.
 */
name: string, 
/**
 * Canonicalized absolute path, free of Windows verbatim prefixes.
 */
workspace_path: string, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. `None` until the project has been opened once.
 */
last_opened_at: string | null, 
/**
 * Whether the workspace folder is present *right now*. Never stored.
 */
workspace_exists: boolean, 
/**
 * The WSL distribution whose filesystem the folder is in, if any.
 *
 * Derived on read, never stored, and never sets `exec_host` (PLAN 7.12):
 * it only hints the picker.
 */
workspace_distro: string | null, 
/**
 * Where this project's commands run (PLAN 7.12); `None` is this computer.
 * Sessions inherit it.
 */
exec_host: ExecHost | null, };

/**
 * What opening a project yields: the project plus its sessions, newest first.
 */
export type ProjectDetail = { project: Project, 
/**
 * The project's sessions, newest first.
 *
 * Filled by [`AppState`], which knows live turn states.
 *
 * [`AppState`]: crate::state::AppState
 */
sessions: Array<SessionSummary>, };

/**
 * Where a proposal stands against the runbook it would become.
 */
export type ProposalState = "pending" | "applied" | "occupied";

/**
 * What one attempt to reach the configured server found.
 */
export type ProviderProbe = { 
/**
 * Whether the server answered as a working OpenAI-compatible endpoint.
 */
ok: boolean, 
/**
 * The HTTP status, when there was one. `None` means nothing answered.
 */
status: number | null, 
/**
 * Round trip in milliseconds, when a response arrived.
 */
latency_ms: number | null, 
/**
 * The diagnosis, written for whoever has to fix it.
 */
message: string, };

/**
 * Who or what produced an answer (PLAN 2.2, `tool:approval_resolved`).
 */
export type ResolvedBy = "user" | "policy" | "timeout";

/**
 * What the brief asks to come back (`COS.md`: `status | artefact | question`).
 *
 * Every return is still a [`Report`]; this changes what a complete one must
 * contain.
 */
export type ReturnFormat = "status" | "artefact" | "question";

/**
 * How alarming a call should look in the approval dialog.
 *
 * Advisory only: the risk badge changes the wording and the colour, never
 * whether something is asked about. Nothing downstream branches on it.
 */
export type Risk = "low" | "medium" | "high";

/**
 * Who produced a message.
 */
export type Role = "user" | "assistant" | "tool" | "system";

/**
 * What an apply did.
 */
export type RosterApplied = { 
/**
 * The identities created, as stored.
 */
created: Array<Agent>, 
/**
 * The names that already existed and were left alone.
 */
skipped: Array<string>, };

/**
 * One proposed identity, as Settings previews it.
 */
export type RosterEntry = { 
/**
 * The name it would be created under.
 */
name: string, 
/**
 * What it is for.
 */
role: string, 
/**
 * The tools it would hold, as the roster names them.
 */
tools: Array<string>, 
/**
 * The runbooks it would hold.
 */
skills: Array<string>, 
/**
 * Its ceiling on scheduled runs.
 */
runs_per_day: number, 
/**
 * What apply would do with it.
 */
state: RosterEntryState, 
/**
 * Why it cannot be created as proposed — which refuses the whole apply.
 * Only a `new` entry is judged: the others are not written.
 */
problem: string | null, 
/**
 * What is true of it and does not block: a runbook it would hold and could
 * not run, or one that is not on this machine yet.
 */
notes: Array<string>, };

/**
 * What apply would do with one proposed identity.
 */
export type RosterEntryState = "new" | "present" | "builtin";

/**
 * A workspace's roster proposal, judged against the identities on file.
 */
export type RosterProposal = { 
/**
 * The `PROPOSAL.md` itself.
 */
path: string, 
/**
 * SHA-256 of the file this preview was built from, hex. Apply is refused
 * unless it is handed back and still matches.
 */
digest: string, 
/**
 * Every identity it proposes, in file order. Empty when it will not parse.
 */
entries: Array<RosterEntry>, 
/**
 * Clocks the founder intends. Apply creates none.
 */
intended_routines: Array<string>, 
/**
 * What the founder could not settle.
 */
open_questions: Array<string>, 
/**
 * Why it will not parse, when it will not.
 */
problem: string | null, 
/**
 * Whether apply would create at least one identity and refuse none.
 */
appliable: boolean, };

/**
 * A routine, as the UI and the scheduler see it.
 */
export type Routine = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * Display name: "Morning watch".
 */
name: string, 
/**
 * The project whose workspace it runs in.
 */
project_id: string, 
/**
 * The identity it runs as.
 */
agent_id: string, 
/**
 * The skill it fires — a live `SKILL.md`, never a chat and never a
 * proposal (PLAN 7.13, *Phase 16's door*).
 */
skill: string, 
/**
 * When it fires.
 */
schedule: Schedule, 
/**
 * What its runs may do with nobody there to ask.
 */
grants: Array<Grant>, 
/**
 * Most runs it may make in one day.
 */
runs_per_day: number, 
/**
 * How many it has made today.
 */
runs_today: number, 
/**
 * Whether the clock is stopped.
 */
paused: boolean, 
/**
 * Why it was stopped, when the scheduler stopped it rather than a person.
 */
paused_reason: string, 
/**
 * When it started counting: set on create, schedule change and un-pause.
 * Earlier windows never fire ([`crate::schedule::due`]).
 */
armed_at: string, 
/**
 * What became of the last run, if it has run.
 */
last: LastRun | null, 
/**
 * Why this routine cannot fire now; derived by
 * [`crate::schedule::inspect`], never stored.
 */
problem: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC.
 */
updated_at: string, };

/**
 * What a create or an update carries.
 */
export type RoutineDraft = { 
/**
 * Display name.
 */
name: string, 
/**
 * The project whose workspace it runs in.
 */
project_id: string, 
/**
 * The identity it runs as.
 */
agent_id: string, 
/**
 * The skill it fires.
 */
skill: string, 
/**
 * When it fires.
 */
schedule: Schedule, 
/**
 * What its runs may do unattended. May be empty — a routine that only
 * reads is the safest thing this document can hold.
 */
grants: Array<Grant>, 
/**
 * Most runs a day. Capped at [`RUNS_PER_DAY_MAX`].
 */
runs_per_day: number, };

/**
 * One run, as the board lists it and the detail pane reads it.
 */
export type Run = { 
/**
 * What ties it together.
 */
run: RunRef, 
/**
 * What to call it: a brief's goal, a routine's name, a runbook's name, a
 * conversation's title. Falls back to the id, which is never nothing.
 */
label: string, 
/**
 * The first thing it did, RFC3339 UTC.
 */
started_at: string, 
/**
 * The last, RFC3339 UTC.
 */
ended_at: string, 
/**
 * The identities that ran under it, in first-appearance order.
 */
agents: Array<string>, 
/**
 * The sessions it touched, likewise. One click each.
 */
sessions: Array<string>, 
/**
 * The runbook it followed, when the run is not itself one.
 */
skill: string, 
/**
 * Every tool call it made, refused and failed ones included.
 */
calls: number, 
/**
 * How many a person was asked about.
 */
asked: number, 
/**
 * How many never ran, because policy or a person refused them.
 */
denied: number, 
/**
 * How many ran and failed.
 */
failed: number, 
/**
 * Which tools, and how often. Most-called first.
 */
tools: Array<Tally>, 
/**
 * What it left on disk: files written, captures taken, artefacts a report
 * named. Paths, never contents — the log never held the contents.
 */
artefacts: Array<string>, 
/**
 * How it ended.
 */
status: RunStatus, 
/**
 * Why, in the words the record already used. Empty when there is nothing
 * to explain.
 */
reason: string, 
/**
 * Tool execution time summed over calls — not wall clock, which excludes
 * waiting on approvals.
 */
tool_ms: number, 
/**
 * What it spent.
 */
cost: Cost, };

/**
 * What kind of work a run was.
 */
export type RunKind = "handoff" | "routine" | "skill" | "session";

/**
 * How a run ended: the three `skill_return` statuses, or no return at all.
 */
export type RunOutcome = "done" | "blocked" | "needs_you" | "failed";

/**
 * What ties a set of audit lines into one run.
 *
 * Also a map key and the value the UI sends back. `session_id` is part of the
 * key except for a delegation, which spans sessions.
 */
export type RunRef = { 
/**
 * What kind of work it was.
 */
kind: RunKind, 
/**
 * The id the lines share: the delegation, the routine, the runbook's
 * name, or the session.
 */
id: string, 
/**
 * The session it happened in. Empty for a delegation.
 */
session_id: string, };

/**
 * How a run ended, in the vocabulary `COS.md` already uses.
 *
 * A report's own statuses, plus [`Ran`](RunStatus::Ran): calls made with no
 * report, like an ordinary conversation.
 */
export type RunStatus = "done" | "blocked" | "needs_you" | "failed" | "ran";

/**
 * One run, and the lines it is replayed from.
 *
 * The replay of PLAN 7.2 row 10: the raw audit entries, in order.
 */
export type RunTrace = { 
/**
 * The run, as the board lists it.
 */
run: Run, 
/**
 * Its lines, oldest first.
 */
entries: Array<AuditEntry>, };

/**
 * What one scaffolding run did: files created and files kept untouched,
 * relative to the root.
 */
export type ScaffoldReport = { 
/**
 * The workspace root the paths are relative to.
 */
root: string, 
/**
 * Files created by this run, in convention order.
 */
created: Array<string>, 
/**
 * Files that were already there and were left exactly as they were.
 */
kept: Array<string>, 
/**
 * Where the history of these files is kept, measured after the run.
 */
versioning: Versioning, 
/**
 * Whether this run created the work tree (vs. one already there).
 */
initialized: boolean, 
/**
 * Why the folder is still not versioned — usually `git` missing, which is
 * not a failure of the scaffold.
 */
problem: string | null, };

/**
 * When a routine fires. A watched folder is the only trigger; anything
 * domain-specific belongs in connectors (PLAN 7.5).
 */
export type Schedule = { "kind": "every", 
/**
 * Minutes between runs, from [`EVERY_MIN_MINUTES`] to
 * [`EVERY_MAX_MINUTES`].
 */
minutes: number, } | { "kind": "daily_at", 
/**
 * Hour of the local day, 0–23.
 */
hour: number, 
/**
 * Minute, 0–59.
 */
minute: number, } | { "kind": "on_change", 
/**
 * The directory, relative to the workspace root: `briefs`, `inbox`.
 */
dir: string, };

/**
 * Why a session exists when a routine opened it (Phase 16). The routine's name
 * is copied so the row still explains itself after a rename or deletion.
 */
export type Scheduled = { 
/**
 * The routine that fired it. Shared with the audit lines the run writes.
 */
routine_id: string, 
/**
 * Its name when it fired.
 */
routine_name: string, 
/**
 * The runbook it was fired to run.
 */
skill: string, };

/**
 * A session and its transcript.
 */
export type SessionDetail = { 
/**
 * The session itself.
 */
session: SessionSummary, 
/**
 * Oldest first — the order the transcript is read in.
 */
messages: Array<Message>, 
/**
 * What has been folded out of the model's context, if anything.
 */
compaction: Compaction | null, 
/**
 * Approvals this session is blocked on, filled by
 * [`AppState::session_detail`](crate::AppState::session_detail) so a
 * reopened window redraws the dialog.
 */
pending_approvals: Array<ApprovalRequest>, };

/**
 * Lifecycle of a session, derived on every read and never stored.
 */
export type SessionState = "idle" | "running" | "awaiting_approval" | "error";

/**
 * One row of a project's session list.
 *
 * `state` is live and `message_count` is derived; neither is stored.
 */
export type SessionSummary = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * The project this session belongs to.
 */
project_id: string, 
/**
 * The identity this session runs as (Phase 12). Always concrete: a session
 * from before identities resolves to
 * [`DEFAULT_AGENT_ID`](super::agents::DEFAULT_AGENT_ID).
 */
agent_id: string, 
/**
 * Display title. Taken from the first user message when not given.
 */
title: string, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. Bumped by every message and every rename.
 */
updated_at: string, 
/**
 * How many messages the transcript holds.
 */
message_count: number, 
/**
 * What the session is doing *right now*.
 */
state: SessionState, 
/**
 * The brief that opened this session (Phase 15), drawn as a badge.
 */
delegated: Delegated | null, 
/**
 * The routine that opened this session (Phase 16). Its own field: a
 * routine's run is not a brief.
 */
scheduled: Scheduled | null, 
/**
 * What the conversation spent (Phase 17), summed on read, never stored.
 */
cost: Cost, };

/**
 * One catalog entry: everything except the body, which only a run
 * [`load`]s.
 */
export type Skill = { 
/**
 * The skill's name, which is its directory's: `inbox.triage`.
 */
name: string, 
/**
 * Where it was found.
 */
scope: SkillScope, 
/**
 * What the author versioned it as. Empty when the file will not parse.
 */
version: string, 
/**
 * The first paragraph of *When to use it*, capped. Empty when it will not
 * parse.
 */
summary: string, 
/**
 * The tools its steps declare they will call.
 */
tools: Array<string>, 
/**
 * The `SKILL.md` itself, so a person can go and open it.
 */
path: string, 
/**
 * Whether this workspace skill hides a library one of the same name, so
 * the panel can say so.
 */
shadows: boolean, 
/**
 * Why this one cannot run. Kept in the catalog for its author, never
 * offered to the model ([`granted`]).
 */
problem: string | null, };

/**
 * One `PROPOSAL.md` in a workspace, as Settings lists it — never its body.
 */
export type SkillProposal = { 
/**
 * The name it would run under, which is its directory's.
 */
name: string, 
/**
 * What the author versioned it as. Empty when it will not parse.
 */
version: string, 
/**
 * The first paragraph of *When to use it*. Empty when it will not parse.
 */
summary: string, 
/**
 * The tools its steps declare.
 */
tools: Array<string>, 
/**
 * The `PROPOSAL.md` itself.
 */
path: string, 
/**
 * The `SKILL.md` applying it would write.
 */
target: string, 
/**
 * Where it stands.
 */
state: ProposalState, 
/**
 * Why it would not run, when it would not. A proposal with a problem is
 * never applied (PLAN 7.13).
 */
problem: string | null, };

/**
 * Which directory a skill was found in. The per-agent scope is an allow-list,
 * not a place.
 */
export type SkillScope = "library" | "workspace";

/**
 * What is true of one declared source right now.
 */
export type SourceState = "in_step" | "drifted" | "missing" | "unrecorded";

/**
 * Where one connector is in its life.
 */
export type State = "off" | "starting" | "ready" | "failed";

/**
 * How a delegated or skill run ended (`COS.md` *Handoff*). "Partly done" is
 * `needs_you` with open questions.
 */
export type Status = "done" | "blocked" | "needs_you";

/**
 * Why a model stopped.
 */
export type StopReason = "stop" | "tool_calls" | "cancelled" | "length" | "error";

/**
 * Which pipe a chunk of tool output came from (PLAN 2.2, `tool:progress`).
 */
export type Stream = "stdout" | "stderr";

/**
 * How many times one tool was called in a run.
 */
export type Tally = { 
/**
 * Tool name.
 */
tool: string, 
/**
 * How many calls.
 */
calls: number, };

/**
 * `tool:approval_resolved` — an approval stopped being pending.
 *
 * Emitted however it ended — answer, cancel or expiry — per `resolved_by`.
 */
export type ToolApprovalResolved = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The request that was answered.
 */
request_id: string, 
/**
 * The call it was about.
 */
call_id: string, 
/**
 * What was decided.
 */
decision: Decision, 
/**
 * Who decided it.
 */
resolved_by: ResolvedBy, };

/**
 * One tool call as the transcript records it: `args_json` verbatim as the
 * model sent it, `summary` one human line, never a blob.
 */
export type ToolCallRecord = { 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * Tool name: `fs_list`, `fs_read`, `fs_write`, ...
 */
tool: string, 
/**
 * The arguments as the model sent them, as a JSON string.
 */
args_json: string, 
/**
 * How far it got.
 */
status: ToolCallStatus, 
/**
 * One human line naming the result, or `null` before there is one.
 */
summary: string | null, 
/**
 * A capture's path for the transcript (PLAN 5.4), persisted so a reopened
 * session shows it. Defaulted for older transcripts.
 */
image_path: string | null, };

/**
 * How far one tool call got.
 */
export type ToolCallStatus = "pending" | "approved" | "denied" | "running" | "ok" | "error" | "cancelled";

/**
 * `tool:drafting` — the model is still writing a call's arguments.
 *
 * The input-side mirror of [`ToolProgress`]: a large `fs_write` streams
 * minutes of arguments with no text, which looks like a hang. Carries a byte
 * count (partial JSON is unreadable), coalesced like `turn:delta`.
 */
export type ToolDrafting = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Which call within this response. There is no call id yet — the model
 * may not have sent one, and the call does not exist until the arguments
 * parse.
 */
index: number, 
/**
 * The tool being called, once the model has named it. `None` while the
 * only thing that has arrived is arguments.
 */
tool: string | null, 
/**
 * Per-turn monotonic counter, as on `turn:delta`. The UI drops anything
 * out of order or repeated.
 */
seq: number, 
/**
 * Bytes of arguments accumulated for this call so far.
 */
bytes: number, };

/**
 * `tool:finished` — the call ended, whatever became of it.
 */
export type ToolFinished = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * How it ended.
 */
outcome: Outcome, 
/**
 * The one human line. Never a raw blob.
 */
summary: string, 
/**
 * How long the execution itself took.
 */
duration_ms: number, 
/**
 * Whether the result the model saw was shorter than what was available.
 */
truncated: boolean, 
/**
 * A capture's path (PLAN 5.4), on the event so the thumbnail shows
 * immediately.
 */
image_path: string | null, };

/**
 * One connector tool, as the rest of the runtime sees it.
 */
export type ToolInfo = { 
/**
 * The connector's id.
 */
connector: string, 
/**
 * The connector's human name, for the dialog and the panel.
 */
connector_name: string, 
/**
 * The tool's own name, as the server spells it.
 */
name: string, 
/**
 * `<connector>__<tool>`: the name in allow-lists, grants and audit lines.
 */
full_name: string, 
/**
 * What the server says the tool does. Reaches the prompt verbatim.
 */
description: string, 
/**
 * Whether the server *claims* the tool only reads; display only.
 */
read_only_hint: boolean, };

/**
 * `tool:progress` — output from a tool that is still running.
 *
 * `shell_exec` only (PLAN 2.2). A coalesced, capped live view, not a record;
 * `tool:finished.truncated` says the pane stopped short.
 */
export type ToolProgress = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * Which pipe this came from.
 */
stream: Stream, 
/**
 * Per-turn monotonic counter, as on `turn:delta`. The UI drops anything
 * out of order or repeated.
 */
seq: number, 
/**
 * The text to append.
 */
chunk: string, };

/**
 * `tool:requested` — the model asked, before policy has judged it.
 */
export type ToolRequested = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The model's id for the call.
 */
call_id: string, 
/**
 * The tool name.
 */
tool: string, 
/**
 * The arguments, redacted the way the audit log redacts them: paths kept
 * whole, long values shortened, file content replaced by its size.
 */
args_redacted: string, };

/**
 * `tool:started` — policy cleared it and it is running.
 */
export type ToolStarted = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * The tool name.
 */
tool: string, };

/**
 * Payload of [`EVENT_TRAY_ACTIVATE`].
 *
 * `action` is `"show"` today. PLAN 2.2 also lists `"new_session"`, for a tray
 * item that starts a session directly; the menu has no such item yet, so the
 * variant is not invented here — a payload the runtime never sends is a
 * branch the UI would carry for nothing.
 */
export type TrayActivate = { 
/**
 * Why the window came forward.
 */
action: string, };

/**
 * One row of the tree.
 */
export type TreeEntry = { 
/**
 * The entry's own name.
 */
name: string, 
/**
 * Relative to the workspace root, with `/`. What the window sends back to
 * expand or preview it.
 */
path: string, 
/**
 * What it is.
 */
kind: EntryKind, 
/**
 * A file's size. `None` for everything else.
 */
bytes: number | null, 
/**
 * Whether it is hidden by default: `.git`, `node_modules`, or named by an
 * ignore file — itself or a folder above it.
 */
ignored: boolean, 
/**
 * A link that lands outside the workspace. Listed so the folder is not
 * misdescribed, and never expanded or previewed.
 */
outside: boolean, 
/**
 * Which part of the convention it is in.
 */
zone: Zone, };

/**
 * One folder of the tree.
 */
export type TreeListing = { 
/**
 * The folder, relative to the workspace root. Empty for the root.
 */
dir: string, 
/**
 * Folders first, then files, by name.
 */
entries: Array<TreeEntry>, 
/**
 * Ignored entries left out of `entries`. Zero when they were asked for.
 */
hidden: number, 
/**
 * Entries past [`LISTING_MAX_ENTRIES`].
 */
more: number, };

/**
 * What one finished turn spent, as the provider reported it (Phase 17),
 * whatever the turn did. `turn_id` joins it to the audit lines;
 * `reported: false` means unknown, not free.
 */
export type TurnCost = { 
/**
 * The turn this is the cost of.
 */
turn_id: string, 
/**
 * Tokens in the requests this turn made, cached ones included.
 */
prompt_tokens: number, 
/**
 * Of those, how many were served from the prompt cache. Defaulted for
 * older records.
 */
cache_read_tokens: number, 
/**
 * Of those, how many were written to the cache.
 */
cache_creation_tokens: number, 
/**
 * Tokens in the replies it got back.
 */
completion_tokens: number, 
/**
 * Whether the provider actually said. `false` means the counts above
 * are zero because nothing was reported, not because nothing was spent.
 */
reported: boolean, 
/**
 * RFC3339, UTC. When the turn finished.
 */
at: string, };

/**
 * `turn:delta` — a frame of assistant text.
 *
 * Coalesced into ~50 ms frames (PLAN 4.2), not one per token.
 */
export type TurnDelta = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Per-turn monotonic counter. The UI drops anything out of order or
 * repeated, which is what makes re-syncing after a reload safe.
 */
seq: number, 
/**
 * The text to append.
 */
text: string, };

/**
 * `turn:error`.
 *
 * Always followed by a `turn:finished` carrying [`StopReason::Error`].
 */
export type TurnError = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * A stable code from PLAN 4.4.
 */
code: string, 
/**
 * What went wrong, written for the user.
 */
message: string, 
/**
 * Whether sending the same thing again could work.
 */
retryable: boolean, };

/**
 * `turn:finished`.
 */
export type TurnFinished = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Why it ended.
 */
stop_reason: StopReason, 
/**
 * What it cost, when the provider said.
 */
usage: Usage | null, };

/**
 * What `session_send` returns (PLAN 2.1): the handle to cancel the turn, which
 * reports through events.
 */
export type TurnHandle = { 
/**
 * The session the turn runs in.
 */
session_id: string, 
/**
 * The turn, unique within the process.
 */
turn_id: string, };

/**
 * `turn:message` — an assistant message, finalized and on disk.
 */
export type TurnMessage = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The message as it was persisted. Replaces the streamed buffer.
 */
message: Message, };

/**
 * `turn:started`.
 */
export type TurnStarted = { 
/**
 * The session the turn runs in.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Which model is answering.
 */
model: string, };

/**
 * What a turn cost, when the provider says.
 */
export type Usage = { 
/**
 * Tokens in the request, whether or not they were paid for at full price.
 *
 * Always the whole prompt: Anthropic's net `input_tokens` get the cache
 * figures added back.
 */
prompt_tokens: number, 
/**
 * Of `prompt_tokens`, how many were served out of the prompt cache — the
 * ones that cost about a tenth of what they would have.
 */
cache_read_tokens: number, 
/**
 * Of `prompt_tokens`, how many were written to the cache for a later turn
 * to read, at a premium over the plain price.
 *
 * Anthropic only; zero elsewhere.
 */
cache_creation_tokens: number, 
/**
 * Tokens in the reply.
 */
completion_tokens: number, 
/**
 * Their sum, as the provider reported it.
 */
total_tokens: number, };

/**
 * Where the history of a workspace's files is kept, if anywhere.
 */
export type Versioning = { 
/**
 * Whether the workspace is in a work tree, and whose.
 */
tree: WorkTree, 
/**
 * The folder holding the `.git`, absolute, or `None`.
 */
at: string | null, };

/**
 * Whether the folder is in a work tree, and whose. An ancestor's counts:
 * [`ensure`] must not split its history.
 */
export type WorkTree = "here" | "ancestor" | "unversioned";

/**
 * `workspace:dropped` — the OS put files on the window.
 *
 * Names and a position, never bytes. The position is in physical pixels from
 * the top left of the webview, as the OS reported it; the window divides by
 * its own scale to find which row the drop landed on.
 */
export type WorkspaceDropped = { 
/**
 * What `workspace_import_brief` is called with.
 */
drop_id: string, 
/**
 * The dropped files' own names, for the line that reports them.
 */
names: Array<string>, 
/**
 * Physical pixels from the left of the webview.
 */
x: number, 
/**
 * Physical pixels from the top of the webview.
 */
y: number, };

/**
 * One directory of the convention, as the UI sees it, measured on every read.
 */
export type WorkspaceEntry = { 
/**
 * The directory relative to the workspace root: `.aegis/briefs`, …
 */
dir: string, 
/**
 * The seed file inside it, relative to the root:
 * `.aegis/status/STATUS.md`, …
 */
file: string, 
/**
 * Whether the directory is there right now.
 */
dir_exists: boolean, 
/**
 * Whether the seed file is there right now.
 */
file_exists: boolean, };

/**
 * The convention's state in one workspace.
 */
export type WorkspaceLayout = { 
/**
 * The workspace root the entries are relative to.
 */
root: string, 
/**
 * Every directory of the convention, present or not.
 */
entries: Array<WorkspaceEntry>, 
/**
 * Whether every directory and seed file is there.
 */
complete: boolean, 
/**
 * Convention directories still at the workspace *root* from the pre-`.aegis`
 * layout (bare names). Reported, never moved.
 */
strays: Array<string>, 
/**
 * Whether the folder is in a git work tree, and whose (PLAN 7.11).
 */
versioning: Versioning, };

/**
 * One file of the constitution, as the panel sees it.
 */
export type WorldFile = { 
/**
 * The path relative to the workspace root: `world/essence.md`.
 */
file: string, 
/**
 * What it is for, in one line.
 */
what: string, 
/**
 * Whether it is there right now.
 */
exists: boolean, };

/**
 * One declared source, as the panel sees it.
 */
export type WorldSource = { 
/**
 * The path as `sources.yml` declares it, relative to the workspace root.
 */
path: string, 
/**
 * What is true of it right now, measured by reading it.
 */
state: SourceState, };

/**
 * The world's state in one workspace, measured on every call.
 */
export type WorldStatus = { 
/**
 * Whether there is a world in this workspace at all.
 */
present: boolean, 
/**
 * Every file of the constitution, present or not, in reading order.
 */
files: Array<WorldFile>, 
/**
 * What `world/sources.yml` declares, and what is true of each one.
 */
sources: Array<WorldSource>, 
/**
 * Whether any declared source has moved since it was perceived.
 */
drifted: boolean, 
/**
 * Why `sources.yml` could not be read as written, when it could not.
 */
problem: string | null, };

/**
 * Which part of the workspace a path is in, as far as a drop is concerned.
 *
 * Lets the window mark the cabinet and pre-refuse drop targets; enforcement is
 * [`intake`](crate::intake)'s.
 */
export type Zone = "plain" | "briefs" | "artefacts" | "cabinet" | "world";
