// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An identity, as the UI and the runtime see it.
 */
export type Agent = { 
/**
 * UUID v4, or [`DEFAULT_AGENT_ID`] for the built-in one.
 */
id: string, 
/**
 * Display name: "Reviewer", "Scribe".
 */
name: string, 
/**
 * What this identity is for, in one line.
 */
role: string, 
/**
 * What it carries into the system message of every request it makes.
 *
 * Empty for the built-in identity, which is what keeps a default session's
 * prompt exactly what it was before identities existed.
 */
instructions: string, 
/**
 * Which provider answers for it. [`DEFAULT_PROVIDER_ID`] today.
 */
provider_id: string, 
/**
 * The tools it may call, in registry order.
 *
 * The allow-list in both directions: the model is shown only these
 * schemas, and policy refuses anything outside the list even when the
 * model asks for it anyway.
 */
tools: Array<string>, 
/**
 * The skills it may run (PLAN 7.3, Phase 13).
 *
 * The per-agent scope of `COS.md` *Skills*: not a directory, but a
 * selection from the runbooks the library and the workspace hold. It
 * never widens [`Agent::tools`] — a skill sequences tools, it does not
 * grant them, and a run whose runbook calls a tool this identity lacks is
 * refused before its first step.
 *
 * Empty for the built-in identity, which is what it was before this phase
 * and stays: a skill is always something someone granted.
 */
skills: Array<string>, 
/**
 * Most scheduled runs it may make in a day (PLAN 7.3, Phase 16).
 *
 * Counted across every routine that fires as this identity, and spent
 * before a run opens a session. Zero is an identity nothing may schedule,
 * which is a real thing to want: a Chief of Staff you talk to and never
 * put on a clock.
 */
runs_per_day: number, 
/**
 * Whether this is the built-in identity, which cannot be edited or
 * deleted. Derived, never stored.
 */
builtin: boolean, };

/**
 * What a create or an update carries.
 *
 * One struct rather than six command arguments: the fields are all strings and
 * lists of strings, and a call site that transposed `name` and `role` would
 * still compile.
 */
export type AgentDraft = { 
/**
 * Display name. Trimmed, and unique among identities.
 */
name: string, 
/**
 * What this identity is for, in one line.
 */
role: string, 
/**
 * What it carries into every request. May be empty.
 */
instructions: string, 
/**
 * Which provider answers for it.
 */
provider_id: string, 
/**
 * Tool names from the registry. May be empty — an identity that only reads
 * and writes prose is a useful thing to be able to make.
 */
tools: Array<string>, 
/**
 * The runbooks it may run. Requires `skill_run` and `skill_return` in
 * [`AgentDraft::tools`] when it is not empty.
 */
skills: Array<string>, 
/**
 * Most scheduled runs a day, capped at [`AGENT_RUNS_PER_DAY_MAX`].
 *
 * `#[serde(default)]` so a caller written before Phase 16 — and the
 * tests that were — still send a valid draft; the default is the same
 * ceiling a new identity gets.
 */
runs_per_day: number, };

/**
 * The structured half of an approval request: what the dialog draws.
 *
 * One variant per tool, so the dialog renders a file path with a size or a
 * command line with its working directory, rather than a JSON blob the user
 * has to parse (PLAN 2.1, `ApprovalDetail`).
 */
export type ApprovalDetail = { "kind": "fs_list", 
/**
 * The resolved directory.
 */
path: string, } | { "kind": "fs_read", 
/**
 * The resolved file.
 */
path: string, 
/**
 * Its size, or `None` when it does not exist yet.
 *
 * Exported as a `number` rather than a `bigint`: this crosses the IPC
 * boundary as JSON, where it is already a double, and a `bigint` in
 * the binding would be a type the value never has at runtime.
 */
bytes: number | null, } | { "kind": "fs_write", 
/**
 * The resolved target.
 */
path: string, 
/**
 * How much would be written. A `number` on the wire — see
 * [`ApprovalDetail::FsRead::bytes`].
 */
bytes: number, 
/**
 * Whether this overwrites something.
 */
exists: boolean, 
/**
 * The first few kilobytes of the content, for the diff pane.
 */
preview: string | null, } | { "kind": "shell", 
/**
 * The program as the model named it.
 */
program: string, 
/**
 * Its arguments, unjoined.
 */
args: Array<string>, 
/**
 * The resolved working directory.
 */
cwd: string, 
/**
 * A display-only rendering of the whole command.
 *
 * Never executed and never parsed: `shell_exec` spawns `program` with
 * `args` directly, with no shell in between (PLAN 5.1). This string
 * exists so a user can read one line instead of five fields.
 */
shell_line: string, 
/**
 * The distribution this lands in, and the working directory as that
 * distribution spells it (PLAN 7.12).
 *
 * `None` — and every dialog before this slice — is this computer, and
 * then `cwd` above is the whole answer. When it is `Some`, `cwd` is
 * still true and still the folder policy contained the call against,
 * but it is no longer the directory the command starts in: the dialog
 * has to show both, or a user would be approving a path the command
 * never sees.
 */
host: ExecTarget | null, } | { "kind": "screen", 
/**
 * Which display, named the way the dialog should say it.
 */
display: string, 
/**
 * Physical width in pixels, `0` when the geometry is not known.
 *
 * A capture crate returns the physical framebuffer, so this is the
 * size of the file that would be written. Both sizes are reported
 * because on a scaled display they differ, and a dialog that showed
 * only one of them would be describing a different picture from the
 * one on the screen (PLAN 5.1).
 */
width: number, 
/**
 * Physical height in pixels, `0` when the geometry is not known.
 */
height: number, 
/**
 * Width in the display's own points — what the user calls its size.
 */
logical_width: number, 
/**
 * Height in the display's own points.
 */
logical_height: number, } | { "kind": "memory", 
/**
 * `preference`, `exception` or `convention`.
 *
 * Not `kind`, which is the enum's own discriminant tag on the wire.
 * The two are different axes — *which tool asked* and *what sort of
 * memory* — and one JSON object cannot spell them the same.
 */
memory_kind: string, 
/**
 * Exactly what would be remembered.
 */
text: string, 
/**
 * What it would rest on, when the model named something.
 */
source: string | null, } | { "kind": "handoff", 
/**
 * One row per brief, in the order they would go out.
 */
briefs: Array<HandoffRow>, 
/**
 * The identity that would review what comes back, when one was named.
 */
reviewer: string | null, 
/**
 * Where the briefs would be filed, when the workspace has a `.aegis/briefs/`.
 */
filed_in: string | null, } | { "kind": "connector", 
/**
 * The connector's id — the part before the `__`.
 */
connector: string, 
/**
 * The connector's name, as the person who installed it wrote it.
 */
connector_name: string, 
/**
 * The tool's own name, as the server spells it.
 */
tool: string, 
/**
 * What the server says the tool does. The server's words, not ours.
 */
description: string, 
/**
 * Whether the server claims the tool only reads. A claim, attributed.
 */
read_only_hint: boolean, 
/**
 * The arguments the model wrote, as indented JSON.
 */
arguments: string, };

/**
 * One approval, as the dialog receives it (PLAN 2.1, `ApprovalRequest`).
 *
 * Half of this comes from [`AskRequest`] — the wording, the badge, the
 * structured detail, the scope — and half is added here: the id to answer
 * with, and the window during which answering it means anything.
 */
export type ApprovalRequest = { 
/**
 * What `approval_resolve` is called with.
 */
request_id: string, 
/**
 * The session whose turn is blocked.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * The tool being asked about.
 */
tool: string, 
/**
 * The badge. Advisory only (PLAN 3.3).
 */
risk: Risk, 
/**
 * The dialog's title: "Write file", "Run shell command".
 */
title: string, 
/**
 * One line naming the thing.
 */
summary: string, 
/**
 * The structured detail the dialog draws.
 */
detail: ApprovalDetail, 
/**
 * What "allow for this session" would cover, in words.
 */
scope_label: string, 
/**
 * Whether `allow_session` is offered at all (PLAN 3.1).
 */
session_grant_allowed: boolean, 
/**
 * Why policy is asking.
 */
reason: string, 
/**
 * When it was raised, fixed-width UTC RFC3339.
 */
requested_at: string, 
/**
 * When it stops being answerable.
 */
expires_at: string, };

/**
 * A file a tool call left on disk, identified without the log holding a copy.
 *
 * `screen_capture` is the only tool that produces one today, and PLAN 5.4
 * names exactly what its line may carry: the path, the dimensions and a
 * digest, never the image. That is enough to say afterwards *which* capture a
 * call produced, and to check that the file still on disk is the one this line
 * is about.
 *
 * The dimensions are pixels because the only artefact so far is an image; a
 * later tool that writes something else will widen this shape rather than
 * borrow it, and the field being optional is what lets it (PLAN 7.1: the audit
 * schema has to be able to grow).
 */
export type AuditArtifact = { 
/**
 * Where the file was written.
 */
path: string, 
/**
 * SHA-256 of the bytes on disk, hex.
 */
sha256: string, 
/**
 * Width in pixels.
 */
width: number, 
/**
 * Height in pixels.
 */
height: number, };

/**
 * How a tool call came to run, or not (PLAN 2.1, `AuditEntry.decision`).
 */
export type AuditDecision = "auto" | "allow_once" | "allow_session" | "deny" | "operator";

/**
 * One line of the log.
 *
 * Serialized and deserialized with the same struct on purpose: the file *is*
 * the wire format for `audit_tail`, so a field the writer adds is a field the
 * reader sees, and there is no second shape to keep in step.
 */
export type AuditEntry = { 
/**
 * RFC3339, UTC, millisecond precision — fixed width, so the file sorts
 * lexicographically in the order it was written.
 */
ts: string, 
/**
 * Which session made the call.
 */
session_id: string, 
/**
 * Which identity it was made as (PLAN 7.3, Phase 12).
 *
 * The first half of "who ran, what did it cost, why did it fail" (PLAN
 * 7.2, row 10). A tool call is gated on the identity's allow-list, so a
 * record of the call that does not name the identity cannot be read back
 * against the grant that let it through.
 *
 * `#[serde(default)]` for the lines written before identities existed: the
 * file is its own wire format, and a reader that refused those lines would
 * lose the history the log is kept for. Those lines carry an empty string,
 * which is not an identity and is drawn as none.
 */
agent_id: string, 
/**
 * Which turn within it.
 */
turn_id: string, 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * Tool name.
 */
tool: string, 
/**
 * The skill run this call was part of (PLAN 7.3, Phase 13).
 *
 * "A run without `skill` on the line cannot be budgeted or replayed"
 * (PLAN 7.6). Every call made between a `skill_run` and its
 * `skill_return` carries the name — not only the two the skill tools make
 * — so the question a replay asks is answerable: *what did this runbook
 * actually do, and what was it refused*.
 *
 * Empty for a call made outside a run, and for every line written before
 * this phase. `#[serde(default)]` for the same reason `agent_id` carries
 * one: the file is its own wire format, and a reader that refused the
 * older lines would lose the history the log is kept for.
 */
skill: string, 
/**
 * The delegation this call was part of (PLAN 7.3, Phase 15).
 *
 * The other half of "one run id over CoS + specialists" (PLAN 7.2, row
 * 10): the CoS's `handoff_delegate` line carries it, and so does every
 * call every specialist makes while working on one of its briefs — in
 * their own sessions, under their own identities. Given `agent_id` beside
 * it, a replay can say who ran, under whose brief, and what it cost.
 *
 * Empty outside a delegation, and on every line written before this
 * phase. `#[serde(default)]` for the reason `agent_id` and `skill` carry
 * one: the file is its own wire format, and a reader that refused the
 * older lines would lose the history the log is kept for.
 */
handoff: string, 
/**
 * The routine whose run this call was part of (PLAN 7.3, Phase 16).
 *
 * The third id over a run, beside `agent_id` and `skill`, and the one that
 * answers a question only this phase can raise: *what did the machine do
 * while nobody was here*. Every call a scheduled run makes carries it, so
 * a week of a watch routine is one grep — and so is the budget it spent,
 * which is the "cannot be budgeted or replayed" of `COS.md` applied to the
 * only runs nobody watched.
 *
 * Empty outside a routine's run, and on every line written before this
 * phase. `#[serde(default)]` for the reason the three before it carry one:
 * the file is its own wire format, and a reader that refused the older
 * lines would lose the history the log is kept for.
 */
routine: string, 
/**
 * Auto-allowed, approved, or refused.
 */
decision: AuditDecision, 
/**
 * Why policy decided that, in the words the user was shown.
 */
policy_reason: string, 
/**
 * SHA-256 of the canonical arguments JSON, hex.
 *
 * The digest is over the arguments in full, including anything the
 * redacted copy shortened, so two calls can be compared for identity even
 * though neither line quotes what they carried.
 */
args_digest: string, 
/**
 * The arguments as JSON, paths kept and values shortened.
 */
args_redacted: string, 
/**
 * How it ended.
 */
outcome: Outcome, 
/**
 * Wall-clock duration of the execution itself.
 */
duration_ms: number, 
/**
 * Bytes the call carried in — the content of a write, nothing for a read.
 */
bytes_in: number, 
/**
 * Bytes the call produced, before any truncation for the model.
 */
bytes_out: number, 
/**
 * The stable code when this failed, `null` otherwise.
 */
error_code: string | null, 
/**
 * The file this call wrote, when it wrote one.
 *
 * `#[serde(default)]` because the file is its own wire format: a log
 * written by an earlier build has no such key, and a reader that refused
 * those lines would lose the history the log exists to keep.
 */
artifact: AuditArtifact | null, };

/**
 * How a configured provider authenticates.
 *
 * Persisted, not a secret: it names a *source*, never a token. `api_key` is
 * the original path (keyring / `AEGIS_API_KEY`), aimed at an OpenAI-compatible
 * host. [`AuthKind::Gemini`] is the same store, a different dialect: Google's
 * Generative Language API, not `/chat/completions`. The CLI variants reuse a
 * login the official agent already wrote on this machine.
 */
export type AuthKind = "api_key" | "gemini" | "claude_cli" | "codex_cli" | "grok_cli";

/**
 * The URL and model Settings prefills for one [`AuthKind`].
 *
 * Not a secret. The form uses this when the user switches authentication so
 * the fields show the CLI's own endpoint instead of a leftover OpenAI URL.
 */
export type AuthPreset = { 
/**
 * Which login this row describes.
 */
auth_kind: AuthKind, 
/**
 * Endpoint used when the base URL field is left empty.
 */
default_base_url: string, 
/**
 * Model id prefilled when the field is empty or still the previous kind's
 * default.
 */
default_model: string, };

/**
 * The board of one project.
 */
export type Board = { 
/**
 * The project it is the board of.
 */
project_id: string, 
/**
 * Where `STATUS.md` is, when it is there. Empty when the convention has
 * not been laid down in this workspace, which is a thing the panel says
 * rather than an error.
 */
status_path: string, 
/**
 * A person has to do something.
 */
attention: Array<BoardItem>, 
/**
 * Something is running.
 */
in_flight: Array<BoardItem>, 
/**
 * Something stopped short.
 */
blocked: Array<BoardItem>, 
/**
 * Every run in the window, newest first.
 */
runs: Array<Run>, 
/**
 * What every session of the project has spent, in total.
 *
 * The whole project rather than the runs, because the runs are a window
 * on the audit log and the sessions are all of them: a total that only
 * counted what was still in the window would fall as the log grew.
 */
cost: Cost, };

/**
 * One line of the board.
 *
 * `BoardItem` on the wire, not `Item`: the generated bindings are one flat
 * namespace shared by every payload in the runtime, and a type called `Item`
 * there would be a name the next phase has to work around.
 */
export type BoardItem = { 
/**
 * The line itself.
 */
text: string, 
/**
 * What is worth knowing beside it: a reason, a runbook, an identity.
 * Empty when the line says it all.
 */
detail: string, 
/**
 * Where it came from.
 */
source: BoardSource, 
/**
 * RFC3339 UTC, when the runtime knows. Empty for a line of the file,
 * which carries no time of its own.
 */
at: string, 
/**
 * The session to open. Empty when there is none to open.
 */
session_id: string, 
/**
 * The routine this is about. Empty when it is not about one.
 */
routine_id: string, 
/**
 * The run to trace, when this line has one.
 */
run: RunRef | null, };

/**
 * Where a line on the board came from.
 *
 * On every item, because the two halves of a board are not equally current
 * and a reader has to be able to tell them apart: the file is what somebody
 * wrote down, the rest is what this process can see for itself.
 */
export type BoardSource = "status" | "approval" | "session" | "routine" | "run";

/**
 * One file that arrived.
 */
export type BriefArrival = { 
/**
 * The name it had where the operator keeps it.
 */
from: string, 
/**
 * Where it is now, relative to the workspace root.
 */
path: string, 
/**
 * How much was copied.
 */
bytes: number, };

/**
 * One file that did not.
 */
export type BriefRefusal = { 
/**
 * The name it had where the operator keeps it.
 */
name: string, 
/**
 * Why it was not copied, in words somebody can act on.
 */
reason: string, };

/**
 * What a session has folded, and what it folded to (PLAN 7.3, Phase 14).
 *
 * A pointer and a summary, never a deletion: `through_message_id` names the
 * last message that no longer reaches the model, and the transcript on disk
 * still holds every one of them. That split is the whole design — the user
 * keeps scrolling through the conversation they had, and the model stops
 * paying for it ([`compact`](crate::compact)).
 */
export type Compaction = { 
/**
 * The last message that folds. Everything after it still reaches the
 * model.
 */
through_message_id: string, 
/**
 * How many messages folded.
 */
folded: number, 
/**
 * What they became: goal, files, decisions, blockers.
 */
state: string, 
/**
 * RFC3339, UTC.
 */
at: string, };

/**
 * One external MCP server, as it is stored.
 */
export type Connector = { 
/**
 * Stable id, and the namespace its tools are offered under.
 */
id: string, 
/**
 * How it is named to a person. Never reaches a tool name.
 */
name: string, 
/**
 * The program to run. Looked up on PATH like any other.
 */
command: string, 
/**
 * Its arguments, passed as a vector — never through a shell.
 */
args: Array<string>, 
/**
 * Environment variables the server needs, by name.
 *
 * The values are read from Aegis' own environment when the child is
 * spawned. A name that is not set there is reported on the row rather
 * than passed as an empty string, because a server that reads an empty
 * token usually fails in a way that is much harder to read.
 */
env: Array<string>, 
/**
 * Whether Aegis starts it at all.
 */
enabled: boolean, };

/**
 * A connector as a person typed it into the form.
 */
export type ConnectorDraft = { 
/**
 * Stable id, and the namespace its tools are offered under.
 */
id: string, 
/**
 * How it is named to a person.
 */
name: string, 
/**
 * The program to run.
 */
command: string, 
/**
 * Its arguments.
 */
args: Array<string>, 
/**
 * Environment variables it needs, by name.
 */
env: Array<string>, 
/**
 * Whether Aegis starts it.
 */
enabled: boolean, };

/**
 * A connector and everything measured about it right now.
 *
 * The record comes from [`ConnectorStore`](crate::store::ConnectorStore); the
 * rest is measured on every read, which is why it is one struct rather than a
 * document with a status column. A stored "connected" is exactly the lie
 * [`store`](crate::store) refuses to hold.
 */
export type ConnectorView = { 
/**
 * The stored record.
 */
connector: Connector, 
/**
 * Where it is right now.
 */
state: State, 
/**
 * What it offers, when it is connected.
 */
tools: Array<ToolInfo>, 
/**
 * Why it is not connected, when it is not.
 */
error: string | null, 
/**
 * The last lines the server wrote to its stderr.
 *
 * The panel shows these because an `npx` that could not resolve a package
 * says so there and nowhere else, and a row reading only "it would not
 * start" is a row nobody can act on.
 */
log: Array<string>, 
/**
 * What the server said about itself, when it got that far.
 */
server: string | null, 
/**
 * The protocol version that was agreed.
 */
protocol: string | null, 
/**
 * Variables it names that are not in this application's environment.
 *
 * Measured, not stored: a token that was exported in the shell Aegis was
 * started from is there for this process and gone for the next one.
 */
missing_env: Array<string>, };

/**
 * Tokens spent over some set of turns (PLAN 7.3, Phase 17).
 *
 * The unit the UI counts in. `unreported` is carried beside the totals rather
 * than folded into them so a number can say how much of itself is missing: a
 * session of ten turns where three providers stayed silent is *at least* this
 * many tokens, and a board that could not say "at least" would be inventing
 * precision it does not have.
 */
export type Cost = { 
/**
 * How many turns were summed.
 */
turns: number, 
/**
 * Of those, how many reported nothing.
 */
unreported: number, 
/**
 * Tokens into the model, cached ones included.
 */
prompt_tokens: number, 
/**
 * Of those, how many were served out of the prompt cache. The share of
 * `prompt_tokens` this is, is how well the prompt is holding its shape.
 */
cache_read_tokens: number, 
/**
 * Of those, how many were written to it.
 */
cache_creation_tokens: number, 
/**
 * Tokens out of it.
 */
completion_tokens: number, };

/**
 * What the user answered (PLAN 2.1, `Decision`).
 */
export type Decision = "allow_once" | "allow_session" | "deny";

/**
 * Why a session exists, when a person did not open it (PLAN 7.3, Phase 15).
 *
 * A delegated run is an ordinary session in every way that matters — same
 * transcript, same approval gate, same audit lines, same identity binding —
 * and this record is the difference: it says which delegation opened it, which
 * session was delegating, and where the brief was filed.
 *
 * It is on the session rather than in a store of its own because a delegated
 * run *is* a session, and a second document listing which sessions are really
 * runs would be a second thing to keep in step with this one. It is also what
 * keeps the work visible: a specialist's session opens in the sidebar like any
 * other, so "what did the reviewer actually do" is a click rather than a
 * forensic exercise (`COS.md` aggregates status for the *CoS*, not for the
 * person).
 */
export type Delegated = { 
/**
 * The delegation this run belongs to. Shared with the audit lines.
 */
handoff_id: string, 
/**
 * The session whose turn handed the brief out.
 */
from_session_id: string, 
/**
 * Where the brief was filed, relative to the workspace root.
 *
 * `None` when the workspace has no `.aegis/briefs/` — the brief then lives only
 * in the first message of this transcript, which is still a record of it.
 */
brief: string | null, };

/**
 * What a row of the tree is.
 */
export type EntryKind = "dir" | "file" | "other";

/**
 * Where a project's commands run.
 *
 * `Option<ExecHost>` is the whole type: `None` — an absent field on disk — is
 * this process, which is what every project had before this slice and what
 * every project still has until somebody says otherwise.
 */
export type ExecHost = { "kind": "wsl", 
/**
 * The distribution's name — `Ubuntu`, `Debian`, `Ubuntu-24.04`.
 */
distro: string, };

/**
 * One choice on the picker.
 *
 * Deliberately not `Option<ExecHost>`: a list of hosts has to be able to say
 * "this computer" as a row like any other, and a `null` in an array is not a
 * row somebody can click.
 */
export type ExecHostOption = { "kind": "host" } | { "kind": "wsl", 
/**
 * The distribution's name.
 */
distro: string, };

/**
 * Where one command will actually land, once policy has resolved it.
 *
 * Built by the decision table, carried on the resolved call, drawn by the
 * approval dialog and read by the tool — one value, so the distribution and
 * the working directory the user *read* are the ones that are *run*, with no
 * second translation anywhere to disagree with the first.
 */
export type ExecTarget = { 
/**
 * The distribution the command runs in.
 */
distro: string, 
/**
 * The working directory, as a path inside that distribution.
 */
cwd: string, };

/**
 * One file, as the preview pane draws it.
 */
export type FilePreview = { 
/**
 * Relative to the workspace root, with `/`.
 */
path: string, 
/**
 * The file's own name.
 */
name: string, 
/**
 * Its size on disk.
 */
bytes: number, 
/**
 * When it last changed, RFC3339 UTC, when the filesystem says.
 */
modified: string | null, 
/**
 * Which part of the convention it is in.
 */
zone: Zone, 
/**
 * What there is to show.
 */
body: PreviewBody, };

/**
 * One `allow_session` grant.
 *
 * The variants are the scopes, not the tools: `fs_read` appears only as
 * [`Grant::FsReadLarge`] because the only `fs_read` row that offers a grant
 * is the large-file one, and a grant that covered every read would be a
 * different, much broader thing than what the user was asked about.
 */
export type Grant = { "kind": "fs_read_large" } | { "kind": "fs_write" } | { "kind": "world_amend" } | { "kind": "shell", 
/**
 * The normalized program key — see [`Grant::shell`].
 */
program: string, } | { "kind": "screen_capture" } | { "kind": "memory_write" } | { "kind": "handoff_delegate" } | { "kind": "connector", 
/**
 * The full tool name the dialog named.
 */
tool: string, };

/**
 * One brief, as the approval dialog draws it.
 */
export type HandoffRow = { 
/**
 * What is to be achieved.
 */
goal: string, 
/**
 * The identity that would do it, as the model named it.
 */
owner: string, 
/**
 * `high`, `normal` or `low`.
 */
priority: string, 
/**
 * `status`, `artefact` or `question`.
 */
return_format: string, 
/**
 * How many paths and links it starts from.
 */
inputs: number, };

/**
 * What one drop did.
 *
 * Two lists, for the reason scaffold's report has two: the operator dropped
 * several things, and the answer to "did they all arrive" has to name the ones
 * that did not.
 */
export type ImportReport = { 
/**
 * Files copied into `.aegis/briefs/`, in the order they were dropped.
 */
arrived: Array<BriefArrival>, 
/**
 * Files left where they were, and why.
 */
refused: Array<BriefRefusal>, };

/**
 * Where the key in use came from (PLAN 2.1, `MaskedSettings`).
 */
export type KeySource = "keyring" | "env" | "claude_cli" | "codex_cli" | "grok_cli" | "none";

/**
 * What became of the last run.
 */
export type LastRun = { 
/**
 * When it started, RFC3339, UTC.
 *
 * The start rather than the end, because it is also what the next fire is
 * counted from: a run that took ten minutes must not be followed by one
 * starting the moment it finishes.
 */
at: string, 
/**
 * The session it ran in, so the transcript is one click away.
 */
session_id: string, 
/**
 * How it ended.
 */
outcome: RunOutcome, 
/**
 * The run's own words: a return's summary, or what went wrong.
 */
detail: string, };

/**
 * Everything the WebView is allowed to know about the provider settings.
 *
 * The name is the contract. There is no unmasked counterpart and no command
 * that returns one: a key can be written and cleared, never read back.
 */
export type MaskedSettings = { 
/**
 * How this provider authenticates.
 */
auth_kind: AuthKind, 
/**
 * The OpenAI-compatible base URL, normalized. Empty when unset.
 */
base_url: string, 
/**
 * The model id sent with every request. Empty when unset.
 */
model: string, 
/**
 * The output ceiling the provider's catalog reported for that model, or
 * `None` for an endpoint that does not publish one.
 *
 * Shown rather than kept internal because its absence is invisible
 * otherwise: a lookup that failed leaves the provider's own conservative
 * default in place, which is the behaviour that made large `fs_write`
 * calls fail silently in the first place. A number here is the panel
 * saying the catalog was actually read.
 */
max_output_tokens: number | null, 
/**
 * Which store answered when the key was last looked for.
 */
key_source: KeySource, 
/**
 * A few characters of the key, for recognition. `None` when there is no
 * key at all.
 */
key_hint: string | null, 
/**
 * Whether this machine has a credential store that answered.
 *
 * `false` on headless Linux and on a locked keychain; the panel then
 * explains the environment variable instead of offering to save a key.
 */
keyring_available: boolean, 
/**
 * Prefill values for every authentication kind, so switching in the form
 * can fill the matching URL and model without a second round trip.
 */
presets: Array<AuthPreset>, };

/**
 * One memory, as the UI and the runtime see it.
 */
export type Memory = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * The identity this belongs to. No accessor spans two.
 */
agent_id: string, 
/**
 * Which of the three it is.
 */
kind: MemoryKind, 
/**
 * The memory itself, in one sentence.
 */
text: string, 
/**
 * What it rests on: a path, a ticket, a person. `None` for a preference
 * somebody simply stated.
 */
source: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. Bumped by a correction, and by a write that repeats
 * something already held.
 */
updated_at: string, };

/**
 * What a create or a correction carries.
 */
export type MemoryDraft = { 
/**
 * Which of the three this is.
 */
kind: MemoryKind, 
/**
 * The memory itself. Trimmed, and never empty.
 */
text: string, 
/**
 * What it rests on, when it rests on something nameable.
 */
source: string | null, };

/**
 * What a memory *is*, which is also the whole vocabulary.
 *
 * Three variants and no `other`. The discipline is the one the seven skill
 * headings impose: naming which of the three a memory is forces whoever
 * writes it to notice when it is none of them, and a memory that is none of
 * them belongs in a file or in a runbook.
 */
export type MemoryKind = "preference" | "exception" | "convention";

/**
 * One message in a transcript.
 */
export type Message = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * Who produced it.
 */
role: Role, 
/**
 * The text. Empty for an assistant message that only made tool calls.
 */
text: string, 
/**
 * The calls this message made. Assistant messages only.
 */
tool_calls: Array<ToolCallRecord>, 
/**
 * Which call this message answers. `tool` messages only.
 */
tool_call_id: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, };

/**
 * What [`list`] found.
 */
export type ModelCatalog = { 
/**
 * Model ids the picker can offer, live ones first when the server answered.
 */
models: Array<string>, 
/**
 * Whether `models` came from the provider just now.
 */
live: boolean, 
/**
 * Empty on a live list. Otherwise why the fallback was used.
 */
message: string, };

/**
 * How a tool call ended (PLAN 2.1, `AuditEntry.outcome`).
 */
export type Outcome = "ok" | "error" | "denied" | "cancelled";

/**
 * What a preview shows.
 */
export type PreviewBody = { "kind": "text", 
/**
 * The first [`TEXT_MAX_BYTES`] of the file, decoded.
 */
text: string, 
/**
 * Whether the file is longer than `text`.
 */
truncated: boolean, 
/**
 * Whether the name says it is markdown.
 */
markdown: boolean, } | { "kind": "image", 
/**
 * The type its first bytes say it is.
 */
mime: string, } | { "kind": "binary", 
/**
 * The type its first bytes say it is, when they say.
 */
mime: string | null, };

/**
 * How soon a brief wants attention.
 *
 * Three words and no number. A scale of ten is a scale nobody calibrates, and
 * what the field is for is the order a board is read in — which of these is
 * waiting on a person, and which can sit.
 */
export type Priority = "high" | "normal" | "low";

/**
 * A project as the UI sees it.
 */
export type Project = { 
/**
 * UUID v4, stable for the life of the project.
 */
id: string, 
/**
 * Display name. Defaults to the workspace folder name.
 */
name: string, 
/**
 * Canonicalized absolute path, free of Windows verbatim prefixes.
 */
workspace_path: string, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. `None` until the project has been opened once.
 */
last_opened_at: string | null, 
/**
 * Whether the workspace folder is present *right now*. Never stored.
 */
workspace_exists: boolean, 
/**
 * The WSL distribution whose filesystem the folder is in, if any.
 *
 * Derived from the path on every read, like `workspace_exists`, and never
 * stored — it is a fact about where the folder is, not a decision anybody
 * made. It is emphatically **not** `exec_host` and never sets it: PLAN
 * 7.12 forbids flipping the host from a `\\wsl$\` path, because picking a
 * folder is not consent. All it does is let the picker mark the row a
 * person is most likely to want, which still takes their click.
 */
workspace_distro: string | null, 
/**
 * Where this project's commands run (PLAN 7.12).
 *
 * `None` is this process — the default, what every project had before this
 * slice, and what a project keeps unless somebody chooses otherwise.
 * Sessions inherit it; they do not override it, because "which operating
 * system does the toolchain live in" is a fact about the folder rather
 * than about a conversation in it.
 */
exec_host: ExecHost | null, };

/**
 * What opening a project yields: the project plus its sessions, newest first.
 */
export type ProjectDetail = { project: Project, 
/**
 * The project's sessions, newest first.
 *
 * Filled by the command layer rather than by [`Store::open`]: a summary
 * carries the session's *live* state, and only [`AppState`] can see both
 * the session document and the turns currently running.
 *
 * [`AppState`]: crate::state::AppState
 */
sessions: Array<SessionSummary>, };

/**
 * What one attempt to reach the configured server found.
 */
export type ProviderProbe = { 
/**
 * Whether the server answered as a working OpenAI-compatible endpoint.
 */
ok: boolean, 
/**
 * The HTTP status, when there was one. `None` means nothing answered.
 */
status: number | null, 
/**
 * Round trip in milliseconds, when a response arrived.
 */
latency_ms: number | null, 
/**
 * The diagnosis, written for whoever has to fix it.
 */
message: string, };

/**
 * Who or what produced an answer (PLAN 2.2, `tool:approval_resolved`).
 */
export type ResolvedBy = "user" | "policy" | "timeout";

/**
 * What the brief asks to come back (`COS.md`: `status | artefact | question`).
 *
 * It does not change the shape of the [`Report`] — every return is a report,
 * which is what makes fan-in cheap. What it changes is what a *complete* one
 * looks like, and the owner is told which was asked for so it can tell the
 * difference between "say what you found" and "produce the file".
 */
export type ReturnFormat = "status" | "artefact" | "question";

/**
 * How alarming a call should look in the approval dialog.
 *
 * Advisory only: the risk badge changes the wording and the colour, never
 * whether something is asked about. Nothing downstream branches on it.
 */
export type Risk = "low" | "medium" | "high";

/**
 * Who produced a message.
 */
export type Role = "user" | "assistant" | "tool" | "system";

/**
 * A routine, as the UI and the scheduler see it.
 */
export type Routine = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * Display name: "Morning watch".
 */
name: string, 
/**
 * The project whose workspace it runs in.
 */
project_id: string, 
/**
 * The identity it runs as.
 */
agent_id: string, 
/**
 * The skill it fires — a live `SKILL.md`, never a chat and never a
 * proposal (PLAN 7.13, *Phase 16's door*).
 */
skill: string, 
/**
 * When it fires.
 */
schedule: Schedule, 
/**
 * What its runs may do with nobody there to ask.
 */
grants: Array<Grant>, 
/**
 * Most runs it may make in one day.
 */
runs_per_day: number, 
/**
 * How many it has made today.
 */
runs_today: number, 
/**
 * Whether the clock is stopped.
 */
paused: boolean, 
/**
 * Why it was stopped, when the scheduler stopped it rather than a person.
 */
paused_reason: string, 
/**
 * When it started counting.
 *
 * Set when the routine is created, and again whenever its schedule changes
 * or somebody un-pauses it. Windows before it do not fire: a routine saved
 * at three in the afternoon and set to run at seven does not immediately
 * decide it is late (see [`crate::schedule::due`]).
 */
armed_at: string, 
/**
 * What became of the last run, if it has run.
 */
last: LastRun | null, 
/**
 * Why this routine cannot fire as it stands.
 *
 * Derived, never stored — the property [`store`](super) holds every
 * document to, and the one that matters most here. A skill that was
 * un-granted, a folder that was unplugged, an identity that was deleted:
 * all facts about *right now*, and a stored copy of any of them is exactly
 * what would let a clock keep firing at a runbook nobody may run. Filled
 * by [`crate::schedule::inspect`].
 */
problem: string | null, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC.
 */
updated_at: string, };

/**
 * What a create or an update carries.
 */
export type RoutineDraft = { 
/**
 * Display name.
 */
name: string, 
/**
 * The project whose workspace it runs in.
 */
project_id: string, 
/**
 * The identity it runs as.
 */
agent_id: string, 
/**
 * The skill it fires.
 */
skill: string, 
/**
 * When it fires.
 */
schedule: Schedule, 
/**
 * What its runs may do unattended. May be empty — a routine that only
 * reads is the safest thing this document can hold.
 */
grants: Array<Grant>, 
/**
 * Most runs a day. Capped at [`RUNS_PER_DAY_MAX`].
 */
runs_per_day: number, };

/**
 * One run, as the board lists it and the detail pane reads it.
 */
export type Run = { 
/**
 * What ties it together.
 */
run: RunRef, 
/**
 * What to call it: a brief's goal, a routine's name, a runbook's name, a
 * conversation's title. Falls back to the id, which is never nothing.
 */
label: string, 
/**
 * The first thing it did, RFC3339 UTC.
 */
started_at: string, 
/**
 * The last, RFC3339 UTC.
 */
ended_at: string, 
/**
 * The identities that ran under it, in the order they first appear.
 *
 * More than one only for a delegation, which is the point of that kind:
 * "who ran" is a list when a Chief of Staff hands work to two specialists.
 */
agents: Array<string>, 
/**
 * The sessions it touched, likewise. One click each.
 */
sessions: Array<string>, 
/**
 * The runbook it followed, when the run is not itself one.
 */
skill: string, 
/**
 * Every tool call it made, refused and failed ones included.
 */
calls: number, 
/**
 * How many a person was asked about.
 */
asked: number, 
/**
 * How many never ran, because policy or a person refused them.
 */
denied: number, 
/**
 * How many ran and failed.
 */
failed: number, 
/**
 * Which tools, and how often. Most-called first.
 */
tools: Array<Tally>, 
/**
 * What it left on disk: files written, captures taken, artefacts a report
 * named. Paths, never contents — the log never held the contents.
 */
artefacts: Array<string>, 
/**
 * How it ended.
 */
status: RunStatus, 
/**
 * Why, in the words the record already used. Empty when there is nothing
 * to explain.
 */
reason: string, 
/**
 * Tool execution time, summed over the calls.
 *
 * Not the wall clock: a run parked for five minutes on an approval dialog
 * did not spend five minutes working, and the two numbers differing is
 * usually the interesting part. The wall clock is `ended_at` less
 * `started_at`, which the UI has both halves of.
 */
tool_ms: number, 
/**
 * What it spent.
 */
cost: Cost, };

/**
 * What kind of work a run was.
 */
export type RunKind = "handoff" | "routine" | "skill" | "session";

/**
 * How a run ended, as the routine list draws it.
 *
 * The first three are the statuses a `skill_return` carries (`COS.md`
 * *Handoff*), which is the whole vocabulary a finished run has. The fourth is
 * what the runtime saw when there was no return at all — a separate value
 * rather than a fourth status, because a `blocked` is an answer and a silence
 * is not (PLAN 7.3, Phase 15, *When nobody answers*).
 */
export type RunOutcome = "done" | "blocked" | "needs_you" | "failed";

/**
 * What ties a set of audit lines into one run.
 *
 * A kind and an id rather than an enum with four payloads, because this is
 * also a map key and a value the UI hands back to ask for one run again.
 * `session_id` is part of the key for everything except a delegation, which
 * is the one kind that spans sessions on purpose.
 */
export type RunRef = { 
/**
 * What kind of work it was.
 */
kind: RunKind, 
/**
 * The id the lines share: the delegation, the routine, the runbook's
 * name, or the session.
 */
id: string, 
/**
 * The session it happened in. Empty for a delegation.
 */
session_id: string, };

/**
 * How a run ended, in the vocabulary `COS.md` already uses.
 *
 * Four words plus one. The first four are a report's own — a run that
 * returned says how it went, and nothing here second-guesses it.
 * [`Ran`](RunStatus::Ran) is the fifth, and it is not a failure: it is work
 * that made calls and never filed a report, which is what an ordinary
 * conversation is.
 */
export type RunStatus = "done" | "blocked" | "needs_you" | "failed" | "ran";

/**
 * One run, and the lines it is replayed from.
 *
 * The replay of PLAN 7.2 row 10, and it is deliberately not a rendering: the
 * entries are the audit lines themselves, in the order they happened, so what
 * the pane shows is what is on disk rather than a story assembled about it.
 * A person reading this is checking the record against the transcript, and a
 * record that had been prettied up first would be worth less than the file.
 */
export type RunTrace = { 
/**
 * The run, as the board lists it.
 */
run: Run, 
/**
 * Its lines, oldest first.
 */
entries: Array<AuditEntry>, };

/**
 * What one scaffolding run did.
 *
 * Two lists rather than a count: the point of the report is that the user can
 * see nothing of theirs was overwritten, and only naming what was kept says
 * that. Paths are relative to the workspace root, in the form the convention
 * is written in.
 */
export type ScaffoldReport = { 
/**
 * The workspace root the paths are relative to.
 */
root: string, 
/**
 * Files created by this run, in convention order.
 */
created: Array<string>, 
/**
 * Files that were already there and were left exactly as they were.
 */
kept: Array<string>, 
/**
 * Where the history of these files is kept, measured after the run.
 */
versioning: Versioning, 
/**
 * Whether this run is what made the folder a work tree.
 *
 * Separate from `versioning` because they answer different questions and a
 * person needs both: *is it versioned* is about the folder, *did you just
 * do that to my folder* is about this press. A repository that was already
 * there reports `versioning` and `initialized: false`.
 */
initialized: boolean, 
/**
 * Why the folder is still not versioned, when it is not.
 *
 * `git` missing from PATH is the ordinary reason and it is not a failure:
 * the directories were the job, they were created, and this is the line
 * that says the other half did not happen.
 */
problem: string | null, };

/**
 * When a routine fires.
 *
 * Three shapes, and the third is the "or a trigger" of PLAN 7.3, Phase 16. It
 * is deliberately the *only* trigger: the sources of truth a routine would
 * really like to watch — mail, a ticket queue, a pull request — arrive as MCP
 * connectors in Phase 18, and a trigger invented here for one of them would be
 * a domain inside the runtime (PLAN 7.5). A folder in the workspace is the one
 * thing this process can already see change.
 */
export type Schedule = { "kind": "every", 
/**
 * Minutes between runs, from [`EVERY_MIN_MINUTES`] to
 * [`EVERY_MAX_MINUTES`].
 */
minutes: number, } | { "kind": "daily_at", 
/**
 * Hour of the local day, 0–23.
 */
hour: number, 
/**
 * Minute, 0–59.
 */
minute: number, } | { "kind": "on_change", 
/**
 * The directory, relative to the workspace root: `briefs`, `inbox`.
 */
dir: string, };

/**
 * Why a session exists, when a clock opened it (PLAN 7.3, Phase 16).
 *
 * The routine's record on the run, and the mirror of [`Delegated`]: a
 * scheduled run is an ordinary session in every way that matters, and this is
 * the difference. The routine's *name* is copied rather than only its id, so a
 * row still says what fired it after the routine has been renamed or deleted —
 * a transcript is a record of something that happened, and it should not stop
 * explaining itself because a document moved on.
 */
export type Scheduled = { 
/**
 * The routine that fired it. Shared with the audit lines the run writes.
 */
routine_id: string, 
/**
 * Its name when it fired.
 */
routine_name: string, 
/**
 * The runbook it was fired to run.
 */
skill: string, };

/**
 * A session and its transcript.
 */
export type SessionDetail = { 
/**
 * The session itself.
 */
session: SessionSummary, 
/**
 * Oldest first — the order the transcript is read in.
 */
messages: Array<Message>, 
/**
 * What has been folded out of the model's context, if anything.
 *
 * On the detail rather than on the summary because it is about the
 * *transcript*, and the summary is a sidebar row: what a fold changes is
 * how the conversation is drawn, and the sidebar does not draw one.
 */
compaction: Compaction | null, 
/**
 * Approvals this session is blocked on.
 *
 * Filled by [`AppState::session_detail`](crate::AppState::session_detail)
 * rather than here: the transcript is on disk, and what a session is
 * waiting for is a fact about this process. It is on the detail at all so
 * that a window reopened mid-turn re-draws the dialog it missed, instead
 * of leaving a turn blocked on a prompt nobody can see.
 */
pending_approvals: Array<ApprovalRequest>, };

/**
 * Lifecycle of a session.
 *
 * Derived from the turn registry on every read, never stored — see the module
 * documentation.
 */
export type SessionState = "idle" | "running" | "awaiting_approval" | "error";

/**
 * One row of a project's session list.
 *
 * `state` is live and `message_count` is derived; neither is stored.
 */
export type SessionSummary = { 
/**
 * UUID v4.
 */
id: string, 
/**
 * The project this session belongs to.
 */
project_id: string, 
/**
 * The identity this session runs as (PLAN 7.3, Phase 12).
 *
 * Always a concrete id, never absent: a session written before identities
 * existed stored nothing, and resolves to
 * [`DEFAULT_AGENT_ID`](super::agents::DEFAULT_AGENT_ID) here. The store
 * keeps the distinction — "chose nothing" and "chose the default" are
 * different facts about a document — and the payload does not, because a
 * UI that had to handle both would draw the same badge twice.
 */
agent_id: string, 
/**
 * Display title. Taken from the first user message when not given.
 */
title: string, 
/**
 * RFC3339, UTC.
 */
created_at: string, 
/**
 * RFC3339, UTC. Bumped by every message and every rename.
 */
updated_at: string, 
/**
 * How many messages the transcript holds.
 */
message_count: number, 
/**
 * What the session is doing *right now*.
 */
state: SessionState, 
/**
 * The brief that opened this session, when one did (PLAN 7.3, Phase 15).
 *
 * `None` for every session a person started, which is every session before
 * this phase. The sidebar draws it as a badge rather than hiding the row:
 * work done on your behalf should be as visible as work you asked for.
 */
delegated: Delegated | null, 
/**
 * The routine that opened this session, when one did (PLAN 7.3, Phase 16).
 *
 * The other way a session comes to exist without anybody typing. It is a
 * second field rather than a variant beside [`SessionSummary::delegated`]
 * because the two are different facts and a session could one day be both
 * — a routine's run is not a brief, and a brief is not on a clock.
 */
scheduled: Scheduled | null, 
/**
 * What the whole conversation has spent (PLAN 7.3, Phase 17).
 *
 * Summed on read from the per-turn records rather than kept as a running
 * total, for the reason `message_count` is: a stored aggregate is a second
 * copy of a fact, and the two disagree the first time anything goes wrong.
 */
cost: Cost, };

/**
 * One catalog entry.
 *
 * Everything except the runbook. A `Skill` is what the panel draws, what the
 * system message is built from, and what the allow-list is matched against;
 * the body is [`load`]ed only by a run, which is the whole point of the type
 * not having a field for it.
 */
export type Skill = { 
/**
 * The skill's name, which is its directory's: `inbox.triage`.
 */
name: string, 
/**
 * Where it was found.
 */
scope: SkillScope, 
/**
 * What the author versioned it as. Empty when the file will not parse.
 */
version: string, 
/**
 * The first paragraph of *When to use it*, capped. Empty when it will not
 * parse.
 */
summary: string, 
/**
 * The tools its steps declare they will call.
 */
tools: Array<string>, 
/**
 * The `SKILL.md` itself, so a person can go and open it.
 */
path: string, 
/**
 * Whether a workspace skill of this name is hiding a library one.
 *
 * Reported rather than silently resolved: two runbooks with one name is
 * exactly the state where somebody is running the one they did not mean
 * to, and the panel can say so.
 */
shadows: boolean, 
/**
 * Why this one cannot run, when it cannot.
 *
 * A file that will not parse stays in the catalog carrying its refusal,
 * rather than disappearing: the author is the only person who can fix it,
 * and a skill that vanished would tell them nothing. It is never offered
 * to the model — [`granted`] drops it.
 */
problem: string | null, };

/**
 * Which of `COS.md`'s scopes a skill was found in.
 *
 * The per-agent scope is not here because it is not a place: it is the
 * identity's allow-list, applied to what these two found.
 */
export type SkillScope = "library" | "workspace";

/**
 * What is true of one declared source right now.
 */
export type SourceState = "in_step" | "drifted" | "missing" | "unrecorded";

/**
 * Where one connector is in its life.
 */
export type State = "off" | "starting" | "ready" | "failed";

/**
 * How a delegated run — or a skill run — ended (`COS.md` *Handoff*).
 *
 * Three states and no fourth. "Partly done" is `needs_you` with the rest in
 * `open_questions`; a runner that offered a fourth would be offering a place
 * to put work nobody then picks up.
 */
export type Status = "done" | "blocked" | "needs_you";

/**
 * Why a model stopped.
 */
export type StopReason = "stop" | "tool_calls" | "cancelled" | "length" | "error";

/**
 * Which pipe a chunk of tool output came from (PLAN 2.2, `tool:progress`).
 */
export type Stream = "stdout" | "stderr";

/**
 * How many times one tool was called in a run.
 */
export type Tally = { 
/**
 * Tool name.
 */
tool: string, 
/**
 * How many calls.
 */
calls: number, };

/**
 * `tool:approval_resolved` — an approval stopped being pending.
 *
 * Emitted for every way one can end, not only for a click: a turn that was
 * cancelled while waiting and a request that expired both produce this, with
 * `resolved_by` saying which. A UI that only removed a card on the user's own
 * answer would leave a dialog on screen for a call nothing will ever run.
 */
export type ToolApprovalResolved = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The request that was answered.
 */
request_id: string, 
/**
 * The call it was about.
 */
call_id: string, 
/**
 * What was decided.
 */
decision: Decision, 
/**
 * Who decided it.
 */
resolved_by: ResolvedBy, };

/**
 * One tool call, as the transcript records it.
 *
 * `args_json` is what the model actually sent, kept verbatim so the card in
 * the UI shows the call that was made rather than the call policy resolved.
 * `summary` is the one human line — never a raw blob, because a transcript
 * that inlines 200 KB of file content is a transcript nobody scrolls.
 */
export type ToolCallRecord = { 
/**
 * The model's own id for the call.
 */
call_id: string, 
/**
 * Tool name: `fs_list`, `fs_read`, `fs_write`, ...
 */
tool: string, 
/**
 * The arguments as the model sent them, as a JSON string.
 */
args_json: string, 
/**
 * How far it got.
 */
status: ToolCallStatus, 
/**
 * One human line naming the result, or `null` before there is one.
 */
summary: string | null, 
/**
 * A local image the call produced, for the transcript to show.
 *
 * Only `screen_capture` sets it, and it is a path rather than the bytes
 * (PLAN 5.4): the WebView loads it through the asset protocol, which is
 * scoped to the capture directory. Persisted, so re-opening a session
 * shows the capture again instead of a line saying one was taken.
 *
 * `#[serde(default)]` for the transcripts written before this field
 * existed — a session on disk must keep opening.
 */
image_path: string | null, };

/**
 * How far one tool call got.
 */
export type ToolCallStatus = "pending" | "approved" | "denied" | "running" | "ok" | "error" | "cancelled";

/**
 * `tool:drafting` — the model is still writing a call's arguments.
 *
 * The mirror of [`ToolProgress`], one step earlier: that one is a tool's
 * *output* while it runs, this is its *input* while it is being written. The
 * gap it fills is the same one, and it opened wider when turns stopped being
 * capped at 8192 output tokens. A file written by `fs_write` is emitted as
 * the arguments of a call, so a large one is twenty thousand tokens that
 * produce no assistant text at all: several minutes in which the runtime is
 * working perfectly and the window has nothing to show. That is
 * indistinguishable from a hang, and people kill turns that look like one.
 *
 * Bytes rather than the text. The arguments are a JSON string being built a
 * fragment at a time, so any prefix of it is malformed, and a pane that
 * streamed it would be showing escaped source with the closing brace missing.
 * A number that climbs answers the only question being asked, which is
 * whether anything is still happening.
 *
 * Coalesced into the same 50 ms window as `turn:delta`, and for the same
 * reason: these fragments arrive far faster than a window can usefully draw.
 */
export type ToolDrafting = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Which call within this response. There is no call id yet — the model
 * may not have sent one, and the call does not exist until the arguments
 * parse.
 */
index: number, 
/**
 * The tool being called, once the model has named it. `None` while the
 * only thing that has arrived is arguments.
 */
tool: string | null, 
/**
 * Per-turn monotonic counter, as on `turn:delta`. The UI drops anything
 * out of order or repeated.
 */
seq: number, 
/**
 * Bytes of arguments accumulated for this call so far.
 */
bytes: number, };

/**
 * `tool:finished` — the call ended, whatever became of it.
 */
export type ToolFinished = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * How it ended.
 */
outcome: Outcome, 
/**
 * The one human line. Never a raw blob.
 */
summary: string, 
/**
 * How long the execution itself took.
 */
duration_ms: number, 
/**
 * Whether the result the model saw was shorter than what was available.
 */
truncated: boolean, 
/**
 * A local image the call produced, for the transcript to show.
 *
 * A path and not the bytes (PLAN 5.4): the WebView loads it through the
 * asset protocol, scoped to the capture directory. Carried on the event
 * as well as persisted on the record so the thumbnail appears when the
 * capture does, rather than when the turn ends and the transcript is
 * re-read.
 */
image_path: string | null, };

/**
 * One connector tool, as the rest of the runtime sees it.
 */
export type ToolInfo = { 
/**
 * The connector's id.
 */
connector: string, 
/**
 * The connector's human name, for the dialog and the panel.
 */
connector_name: string, 
/**
 * The tool's own name, as the server spells it.
 */
name: string, 
/**
 * The name the model is given: `<connector>__<tool>`.
 *
 * This is the string an identity's allow-list holds, the string a session
 * grant is keyed on, and the string the audit line records. There is one
 * spelling, and it is this one.
 */
full_name: string, 
/**
 * What the server says the tool does. Reaches the prompt verbatim.
 */
description: string, 
/**
 * Whether the server *claims* the tool only reads.
 *
 * Shown in the approval dialog, attributed to the server. Nothing in this
 * runtime branches on it.
 */
read_only_hint: boolean, };

/**
 * `tool:progress` — output from a tool that is still running.
 *
 * `shell_exec` only (PLAN 2.2): a file is read in one call, but a command can
 * take two minutes, and a pane that only fills in at the end is
 * indistinguishable from a hang.
 *
 * Frames are coalesced to roughly 50 ms and the total is capped, so this is
 * a live view rather than a record — the transcript keeps the one-line
 * summary and the audit log keeps the byte counts. A `tool:finished` carrying
 * `truncated` is what says the pane stopped short of everything the command
 * printed.
 */
export type ToolProgress = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * Which pipe this came from.
 */
stream: Stream, 
/**
 * Per-turn monotonic counter, as on `turn:delta`. The UI drops anything
 * out of order or repeated.
 */
seq: number, 
/**
 * The text to append.
 */
chunk: string, };

/**
 * `tool:requested` — the model asked, before policy has judged it.
 */
export type ToolRequested = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The model's id for the call.
 */
call_id: string, 
/**
 * The tool name.
 */
tool: string, 
/**
 * The arguments, redacted the way the audit log redacts them: paths kept
 * whole, long values shortened, file content replaced by its size.
 */
args_redacted: string, };

/**
 * `tool:started` — policy cleared it and it is running.
 */
export type ToolStarted = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The call.
 */
call_id: string, 
/**
 * The tool name.
 */
tool: string, };

/**
 * Payload of [`EVENT_TRAY_ACTIVATE`].
 *
 * `action` is `"show"` today. PLAN 2.2 also lists `"new_session"`, for a tray
 * item that starts a session directly; the menu has no such item yet, so the
 * variant is not invented here — a payload the runtime never sends is a
 * branch the UI would carry for nothing.
 */
export type TrayActivate = { 
/**
 * Why the window came forward.
 */
action: string, };

/**
 * One row of the tree.
 */
export type TreeEntry = { 
/**
 * The entry's own name.
 */
name: string, 
/**
 * Relative to the workspace root, with `/`. What the window sends back to
 * expand or preview it.
 */
path: string, 
/**
 * What it is.
 */
kind: EntryKind, 
/**
 * A file's size. `None` for everything else.
 */
bytes: number | null, 
/**
 * Whether it is hidden by default: `.git`, `node_modules`, or named by an
 * ignore file — itself or a folder above it.
 */
ignored: boolean, 
/**
 * A link that lands outside the workspace. Listed so the folder is not
 * misdescribed, and never expanded or previewed.
 */
outside: boolean, 
/**
 * Which part of the convention it is in.
 */
zone: Zone, };

/**
 * One folder of the tree.
 */
export type TreeListing = { 
/**
 * The folder, relative to the workspace root. Empty for the root.
 */
dir: string, 
/**
 * Folders first, then files, by name.
 */
entries: Array<TreeEntry>, 
/**
 * Ignored entries left out of `entries`. Zero when they were asked for.
 */
hidden: number, 
/**
 * Entries past [`LISTING_MAX_ENTRIES`].
 */
more: number, };

/**
 * What one turn spent, as the provider reported it (PLAN 7.3, Phase 17).
 *
 * One record per finished turn, whatever the turn did — a reply that only
 * talked costs tokens as surely as one that ran six tools, and a ledger that
 * only counted the second kind would answer "what did it cost" with a number
 * nobody could reconcile against a bill.
 *
 * `turn_id` is the same id the audit line carries, which is the whole reason
 * this can be joined to a run: the log says *which* turns a delegation or a
 * runbook made its calls in, and this says what each of those turns spent.
 *
 * `reported` is the honesty flag. Not every OpenAI-compatible server sends a
 * `usage` object, and a turn whose cost is unknown is recorded as unknown
 * rather than as zero — a counter that quietly added nothing would read as a
 * free turn, which is the one thing it certainly was not.
 */
export type TurnCost = { 
/**
 * The turn this is the cost of.
 */
turn_id: string, 
/**
 * Tokens in the requests this turn made, cached ones included.
 */
prompt_tokens: number, 
/**
 * Of those, how many were served out of the prompt cache.
 *
 * Defaulted rather than required: sessions charged before this was
 * recorded are read back as turns that cached nothing, which is what a
 * turn that predates the field did.
 */
cache_read_tokens: number, 
/**
 * Of those, how many were written to the cache.
 */
cache_creation_tokens: number, 
/**
 * Tokens in the replies it got back.
 */
completion_tokens: number, 
/**
 * Whether the provider actually said. `false` means the counts above
 * are zero because nothing was reported, not because nothing was spent.
 */
reported: boolean, 
/**
 * RFC3339, UTC. When the turn finished.
 */
at: string, };

/**
 * `turn:delta` — a frame of assistant text.
 *
 * Deltas are coalesced into roughly 50 ms frames before they are sent
 * (PLAN 4.2), so this is a phrase rather than a token: waking the WebView
 * once per token is what makes a streamed reply feel slower than a batched
 * one.
 */
export type TurnDelta = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Per-turn monotonic counter. The UI drops anything out of order or
 * repeated, which is what makes re-syncing after a reload safe.
 */
seq: number, 
/**
 * The text to append.
 */
text: string, };

/**
 * `turn:error`.
 *
 * Always followed by a `turn:finished` carrying [`StopReason::Error`], so a
 * UI that only tracks the lifecycle does not have to special-case failure to
 * re-enable its composer.
 */
export type TurnError = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * A stable code from PLAN 4.4.
 */
code: string, 
/**
 * What went wrong, written for the user.
 */
message: string, 
/**
 * Whether sending the same thing again could work.
 */
retryable: boolean, };

/**
 * `turn:finished`.
 */
export type TurnFinished = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Why it ended.
 */
stop_reason: StopReason, 
/**
 * What it cost, when the provider said.
 */
usage: Usage | null, };

/**
 * What `session_send` hands back (PLAN 2.1).
 *
 * The turn itself is reported through events; this is only the handle needed
 * to cancel it.
 */
export type TurnHandle = { 
/**
 * The session the turn runs in.
 */
session_id: string, 
/**
 * The turn, unique within the process.
 */
turn_id: string, };

/**
 * `turn:message` — an assistant message, finalized and on disk.
 */
export type TurnMessage = { 
/**
 * The session.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * The message as it was persisted. Replaces the streamed buffer.
 */
message: Message, };

/**
 * `turn:started`.
 */
export type TurnStarted = { 
/**
 * The session the turn runs in.
 */
session_id: string, 
/**
 * The turn.
 */
turn_id: string, 
/**
 * Which model is answering.
 */
model: string, };

/**
 * What a turn cost, when the provider says.
 */
export type Usage = { 
/**
 * Tokens in the request, whether or not they were paid for at full price.
 *
 * The *whole* prompt, always — which is the one definition that means the
 * same thing across providers and across a cache hit. Anthropic reports
 * its own `input_tokens` net of both cache figures below, so the provider
 * puts them back before filling this in; the Responses API counts them in
 * already and does not. Getting that wrong would make a well-cached turn
 * look like a cheap one instead of a cheaply-*served* one.
 */
prompt_tokens: number, 
/**
 * Of `prompt_tokens`, how many were served out of the prompt cache — the
 * ones that cost about a tenth of what they would have.
 */
cache_read_tokens: number, 
/**
 * Of `prompt_tokens`, how many were written to the cache for a later turn
 * to read, at a premium over the plain price.
 *
 * Anthropic only: providers whose caching is automatic charge nothing to
 * write and so report nothing, which is a zero here rather than a gap.
 */
cache_creation_tokens: number, 
/**
 * Tokens in the reply.
 */
completion_tokens: number, 
/**
 * Their sum, as the provider reported it.
 */
total_tokens: number, };

/**
 * Where the history of a workspace's files is kept, if anywhere.
 */
export type Versioning = { 
/**
 * Whether the workspace is in a work tree, and whose.
 */
tree: WorkTree, 
/**
 * The folder holding the `.git`, absolute — `None` when there is none.
 *
 * Named rather than left implicit because the answer a person needs from
 * [`WorkTree::Ancestor`] is *which* folder: "this is inside a repository"
 * is only useful once you can see whether it is the one you meant.
 */
at: string | null, };

/**
 * Whether the folder is in a work tree, and whose.
 *
 * Three answers rather than a boolean because the middle one changes what the
 * panel should say and what [`ensure`] must not do: a workspace inside a
 * larger repository is already versioned, and initialising it would split the
 * history it is already part of.
 */
export type WorkTree = "here" | "ancestor" | "unversioned";

/**
 * `workspace:dropped` — the OS put files on the window.
 *
 * Names and a position, never bytes. The position is in physical pixels from
 * the top left of the webview, as the OS reported it; the window divides by
 * its own scale to find which row the drop landed on.
 */
export type WorkspaceDropped = { 
/**
 * What `workspace_import_brief` is called with.
 */
drop_id: string, 
/**
 * The dropped files' own names, for the line that reports them.
 */
names: Array<string>, 
/**
 * Physical pixels from the left of the webview.
 */
x: number, 
/**
 * Physical pixels from the top of the webview.
 */
y: number, };

/**
 * One directory of the convention, as the UI sees it.
 *
 * Both flags are measured on every read and never stored: a user can create
 * `decisions/` in a terminal, or delete it, and the panel has to be right
 * about a folder it does not own.
 */
export type WorkspaceEntry = { 
/**
 * The directory relative to the workspace root: `.aegis/briefs`, …
 */
dir: string, 
/**
 * The seed file inside it, relative to the root:
 * `.aegis/status/STATUS.md`, …
 */
file: string, 
/**
 * Whether the directory is there right now.
 */
dir_exists: boolean, 
/**
 * Whether the seed file is there right now.
 */
file_exists: boolean, };

/**
 * The convention's state in one workspace.
 */
export type WorkspaceLayout = { 
/**
 * The workspace root the entries are relative to.
 */
root: string, 
/**
 * Every directory of the convention, present or not.
 */
entries: Array<WorkspaceEntry>, 
/**
 * Whether every directory and seed file is there.
 *
 * Derived here rather than in the UI, so that "set up" means the same
 * thing to the panel, to a test, and to whatever later phase asks.
 */
complete: boolean, 
/**
 * Convention directories found at the workspace *root*, from the layout
 * this build no longer uses. Bare names: `briefs`, `decisions`, …
 *
 * The cabinet moved under [`CABINET_DIR`], and a folder set up before that
 * still has its `.aegis/status/STATUS.md` where it always was — full of work the
 * runtime has just stopped being able to see. So they are named, and that
 * is all: nothing here moves a directory in somebody's repository. Picking
 * a folder was never consent to rearrange it, and the same rule that keeps
 * [`scaffold`] from overwriting a file keeps this from relocating one.
 *
 * Empty for every workspace that never had the old layout, which is the
 * ordinary case and draws nothing.
 */
strays: Array<string>, 
/**
 * Whether the folder is in a git work tree, and whose (PLAN 7.11).
 *
 * A fact about the convention, like the four ticks, and reported for the
 * same reason: these files are a shared memory, and a shared memory with
 * no history is a board nobody can read backwards. It is not the start of
 * a git client — there is no log here, no stage and no push, and the only
 * thing that ever changes it is the button beside it.
 */
versioning: Versioning, };

/**
 * One file of the constitution, as the panel sees it.
 */
export type WorldFile = { 
/**
 * The path relative to the workspace root: `world/essence.md`.
 */
file: string, 
/**
 * What it is for, in one line.
 */
what: string, 
/**
 * Whether it is there right now.
 */
exists: boolean, };

/**
 * One declared source, as the panel sees it.
 */
export type WorldSource = { 
/**
 * The path as `sources.yml` declares it, relative to the workspace root.
 */
path: string, 
/**
 * What is true of it right now, measured by reading it.
 */
state: SourceState, };

/**
 * The world's state in one workspace.
 *
 * Measured on every call and never stored, for the reason
 * [`WorkspaceLayout`](crate::workspace::WorkspaceLayout) is: the folder
 * belongs to the user, who may have written `world/essence.md` in their editor
 * a minute ago.
 */
export type WorldStatus = { 
/**
 * Whether there is a world in this workspace at all.
 *
 * False for every workspace that never opted in, which is most of them,
 * and the panel then says only what a world is and how one is started.
 */
present: boolean, 
/**
 * Every file of the constitution, present or not, in reading order.
 */
files: Array<WorldFile>, 
/**
 * What `world/sources.yml` declares, and what is true of each one.
 */
sources: Array<WorldSource>, 
/**
 * Whether any declared source has moved since it was perceived.
 *
 * Derived here rather than in the UI so that "drifted" means the same
 * thing to the panel, to the brief that will not launch, and to a test.
 */
drifted: boolean, 
/**
 * Why `sources.yml` could not be read as written, when it could not.
 */
problem: string | null, };

/**
 * Which part of the workspace a path is in, as far as a drop is concerned.
 *
 * Measured here rather than in the window so the convention's names are
 * spelled in one language. The window uses it for two things: marking the
 * cabinet as the working surface, and refusing a drop before it asks —
 * [`intake`](crate::intake) takes no destination at all, so a refusal there
 * is the window being honest about a target, not the enforcement.
 */
export type Zone = "plain" | "briefs" | "artefacts" | "cabinet" | "world";
